import type { Copy, EvidenceCard, Locale, LocalizedList, LocalizedText, NoiseType, Preset } from './types';

export const copy: Record<Locale, Copy> = {
  ja: {
    appName: 'Noise Generator',
    appTagline: 'シンプルに、静かに、聞きたい音だけ。',
    install: 'ホーム画面に追加',
    installHint: 'ホーム画面に追加すると、起動が速くなります。',
    play: '再生',
    stop: '停止',
    addToHomeScreen: 'ホーム画面に追加',
    evidenceTitle: '説明と論文',
    platformTitle: 'PWA と端末差分',
    simpleExplanationTitle: '短い説明',
    volumeLabel: '音量',
    timerLabel: 'タイマー',
    timerOff: 'なし',
    installInfo: 'インストール情報を表示',
    addHome: 'ホーム画面に追加',
    aboutBackground: 'バックグラウンドでの動作について',
    noiseType: 'ノイズタイプ',
    noisePapers: 'ノイズの論文リンクを表示',
    noiseReferences: 'ノイズに関する参考論文',
    beatOn: 'ビート ON',
    beatLabel: 'ビート',
    beatHelp: 'ビートの説明を表示',
    beatDesc: '左右で異なる音（バイノーラル）または等間隔のパルス（アイソクロニック）を流し、集中や休息を助ける機能です。',
    earphoneMode: 'イヤホン（バイノーラル）',
    speakerMode: 'スピーカー（アイソクロニック）',
    baseFreq: 'ベース周波数',
    currentBand: '実際の再生周波数',
    footerNote: '医療効果を保証するものではありません。用途に合わせて慎重に使ってください。',
    minute: '分',
    second: '秒',
    iosStep1: '共有ボタン（四角に上矢印）をタップします。',
    iosStep2: '下にスクロールして「ホーム画面に追加」をタップします。',
    iosStep3: '右上の「追加」をタップします。',
    androidStep1: 'ブラウザの3点リーダーメニューをタップします。',
    androidStep2: '「アプリをインストール」または「ホーム画面に追加」をタップします。',
    gotIt: '了解',
    close: '閉じる',
    presetsTitle: 'クイックプリセット',
    resetPreset: '設定をリセット',
    settingsTitle: '詳細設定',
    advancedSettings: '詳細設定を表示',
    noiseOff: 'オフ',
    edit: '編集',
    resetPresetsDescription: 'クイックプリセットを初期状態にする',
    presetEditorTitle: 'プリセット編集',
    presetNameLabel: 'プリセット名',
    presetDescriptionLabel: '説明',
    applyAndSave: '適用して保存',
    noNoise: 'ノイズなし',
    waveSuffix: '波'
  },
  en: {
    appName: 'Noise Generator',
    appTagline: 'Simple noise and beats, tuned for phones.',
    install: 'Add to Home Screen',
    installHint: 'Adding to the home screen makes launch faster.',
    play: 'Play',
    stop: 'Stop',
    addToHomeScreen: 'Add to Home Screen',
    evidenceTitle: 'Explanation and papers',
    platformTitle: 'PWA and platform differences',
    simpleExplanationTitle: 'Plain explanation',
    volumeLabel: 'Volume',
    timerLabel: 'Timer',
    timerOff: 'Off',
    installInfo: 'Show installation info',
    addHome: 'Add to home screen',
    aboutBackground: 'About background playback',
    noiseType: 'Noise type',
    noisePapers: 'Show noise papers',
    noiseReferences: 'References for noise studies',
    beatOn: 'Beat on',
    beatLabel: 'Beat',
    beatHelp: 'Show beat help',
    beatDesc: 'This sends slightly different tones to each ear (binaural) or pulsed tones (isochronic) to help focus or rest.',
    earphoneMode: 'Earphones (Binaural)',
    speakerMode: 'Speakers (Isochronic)',
    baseFreq: 'Base frequency',
    currentBand: 'Current playback frequencies',
    footerNote: 'No medical claims are made. Use it cautiously and fit it to your context.',
    minute: 'm',
    second: 's',
    iosStep1: 'Tap the Share button (square with arrow up).',
    iosStep2: 'Scroll down and tap "Add to Home Screen".',
    iosStep3: 'Tap "Add" in the top right.',
    androidStep1: 'Tap the three-dot menu in the browser.',
    androidStep2: 'Tap "Install app" or "Add to home screen".',
    gotIt: 'Got it',
    close: 'Close',
    presetsTitle: 'Quick Presets',
    resetPreset: 'Reset Settings',
    settingsTitle: 'Advanced Settings',
    advancedSettings: 'Show advanced settings',
    noiseOff: 'Off',
    edit: 'Edit',
    resetPresetsDescription: 'Reset quick presets',
    presetEditorTitle: 'Preset Editor',
    presetNameLabel: 'Preset Name',
    presetDescriptionLabel: 'Description',
    applyAndSave: 'Apply and Save',
    noNoise: 'No noise',
    waveSuffix: ' wave'
  },
  'zh-Hans': {
    appName: 'Noise Generator',
    appTagline: '简洁、安静，只播放你想听的声音。',
    install: '添加到主屏幕',
    installHint: '添加到主屏幕后，启动会更快。',
    play: '播放',
    stop: '停止',
    addToHomeScreen: '添加到主屏幕',
    evidenceTitle: '说明与论文',
    platformTitle: 'PWA 与设备差异',
    simpleExplanationTitle: '简短说明',
    volumeLabel: '音量',
    timerLabel: '计时器',
    timerOff: '关闭',
    installInfo: '显示安装信息',
    addHome: '添加到主屏幕',
    aboutBackground: '关于后台播放',
    noiseType: '噪音类型',
    noisePapers: '显示噪音论文',
    noiseReferences: '噪音研究参考',
    beatOn: '开启双耳节拍',
    beatLabel: '节拍',
    beatHelp: '显示双耳节拍帮助',
    beatDesc: '向每只耳朵发送略有不同的音调，以便更清晰地感知节拍差异。',
    earphoneMode: '耳机（双耳）',
    speakerMode: '扬声器（等时线）',
    baseFreq: '基准频率',
    currentBand: '当前节拍频带',
    footerNote: '不作医疗声明。请谨慎使用并适应您的环境。',
    minute: '分',
    second: '秒',
    iosStep1: '点击“分享”按钮（带上箭头的方块）。',
    iosStep2: '向下滚动并点击“添加到主屏幕”。',
    iosStep3: '点击右上角的“添加”。',
    androidStep1: '点击浏览器中的三点菜单。',
    androidStep2: '点击“安装应用”或“添加到主屏幕”。',
    gotIt: '知道了',
    close: '关闭',
    presetsTitle: '快速预设',
    resetPreset: '重置设置',
    settingsTitle: '高级设置',
    advancedSettings: '显示高级设置',
    noiseOff: '关闭',
    edit: '编辑',
    resetPresetsDescription: '重置快速预设',
    presetEditorTitle: '预设编辑器',
    presetNameLabel: '预设名称',
    presetDescriptionLabel: '描述',
    applyAndSave: '应用并保存',
    noNoise: '无噪音',
    waveSuffix: '波'
  },
  es: {
    appName: 'Noise Generator',
    appTagline: 'Simple, tranquilo, solo el sonido que quieres.',
    install: 'Agregar a pantalla de inicio',
    installHint: 'Agregarla a la pantalla de inicio acelera el inicio.',
    play: 'Reproducir',
    stop: 'Detener',
    addToHomeScreen: 'Agregar a pantalla de inicio',
    evidenceTitle: 'Explicación y estudios',
    platformTitle: 'PWA y diferencias de plataforma',
    simpleExplanationTitle: 'Explicación breve',
    volumeLabel: 'Volumen',
    timerLabel: 'Temporizador',
    timerOff: 'Desactivado',
    installInfo: 'Mostrar info de instalación',
    addHome: 'Agregar a la pantalla de inicio',
    aboutBackground: 'Sobre reproducción en segundo plano',
    noiseType: 'Tipo de ruido',
    noisePapers: 'Mostrar estudios de ruido',
    noiseReferences: 'Referencias para estudios de ruido',
    beatOn: 'Pulsos binaurales activados',
    beatLabel: 'Pulso',
    beatHelp: 'Mostrar ayuda de pulsos binaurales',
    beatDesc: 'Envía tonos ligeramente diferentes a cada oído para que la diferencia de pulso se perciba más claramente.',
    earphoneMode: 'Auriculares (Binaural)',
    speakerMode: 'Altavoces (Isocrónico)',
    baseFreq: 'Frecuencia base',
    currentBand: 'Banda de pulso actual',
    footerNote: 'No se realizan afirmaciones médicas. Úselo con precaución y adáptelo a su contexto.',
    minute: 'm',
    second: 's',
    iosStep1: 'Toca el botón Compartir (cuadrado con flecha arriba).',
    iosStep2: 'Desplázate hacia abajo y toca "Agregar a pantalla de inicio".',
    iosStep3: 'Toca "Agregar" en la esquina superior derecha.',
    androidStep1: 'Toca el menú de three puntos en el navegador.',
    androidStep2: 'Toca "Instalar aplicación" o "Agregar a pantalla de inicio".',
    gotIt: 'Entendido',
    close: 'Cerrar',
    presetsTitle: 'Ajustes rápidos',
    resetPreset: 'Restablecer ajustes',
    settingsTitle: 'Ajustes avanzados',
    advancedSettings: 'Mostrar ajustes avanzados',
    noiseOff: 'Apagado',
    edit: 'Editar',
    resetPresetsDescription: 'Restablecer ajustes rápidos',
    presetEditorTitle: 'Editor de ajustes',
    presetNameLabel: 'Nombre del ajuste',
    presetDescriptionLabel: 'Descripción',
    applyAndSave: 'Aplicar y guardar',
    noNoise: 'Sin ruido',
    waveSuffix: ' onda'
  },
  hi: {
    appName: 'Noise Generator',
    appTagline: 'सरल, शांत, बस वही ध्वनि जो आप सुनना चाहें।',
    install: 'होम स्क्रीन पर जोड़ें',
    installHint: 'होम स्क्रीन पर जोड़ने से ऐप जल्दी खुलता है।',
    play: 'चलाएँ',
    stop: 'रोकें',
    addToHomeScreen: 'होम स्क्रीन पर जोड़ें',
    evidenceTitle: 'व्याख्या और शोध पत्र',
    platformTitle: 'PWA और प्लेटफ़ॉर्म अंतर',
    simpleExplanationTitle: 'संक्षिप्त व्याख्या',
    volumeLabel: 'आवाज़',
    timerLabel: 'टाइमर',
    timerOff: 'बंद',
    installInfo: 'इंस्टॉलेशन जानकारी दिखाएं',
    addHome: 'होम स्क्रीन पर जोड़ें',
    aboutBackground: 'बैकग्राउंड प्लेबैक के बारे में',
    noiseType: 'शोर का प्रकार',
    noisePapers: 'शोर शोध पत्र दिखाएं',
    noiseReferences: 'शोर अध्ययन के संदर्भ',
    beatOn: 'बाइनोरल बीट्स चालू',
    beatLabel: 'बीट',
    beatHelp: 'बाइनोरल बीट सहायता दिखाएं',
    beatDesc: 'प्रत्येक कान में थोड़े अलग टोन भेजता है ताकि बीट अंतर को अधिक स्पष्ट रूप से समझा जा सके।',
    earphoneMode: 'इयरफ़ोन (बाइनोरल)',
    speakerMode: 'स्पीकर (आइसोक्रोनिक)',
    baseFreq: 'आधार आवृत्ति',
    currentBand: 'वर्तमान बीट बैंड',
    footerNote: 'कोई चिकित्सा दावा नहीं किया गया है। इसका सावधानीपूर्वक उपयोग करें और अपने संदर्भ के अनुसार ढालें।',
    minute: 'म',
    second: 'से',
    iosStep1: 'शेयर बटन (ऊपर तीर वाला वर्ग) पर टैप करें।',
    iosStep2: 'नीचे स्क्रॉल करें और "होम स्क्रीन पर जोड़ें" पर टैप करें।',
    iosStep3: 'ऊपर दाईं ओर "जोड़ें" पर टैप करें।',
    androidStep1: 'ब्राउज़र में तीन-बिंदू वाले मेनू पर टैप करें।',
    androidStep2: '"ऐप इंस्टॉल करें" या "होम स्क्रीन पर जोड़ें" पर टैप करें।',
    gotIt: 'समझ गए',
    close: 'बंद करें',
    presetsTitle: 'त्वरित प्रीसेट',
    resetPreset: 'सेटिंग्स रीसेट करें',
    settingsTitle: 'उन्नत सेटिंग्स',
    advancedSettings: 'उन्नत सेटिंग्स दिखाएं',
    noiseOff: 'बंद',
    edit: 'संपादित करें',
    resetPresetsDescription: 'त्वरित प्रीसेट रीसेट करें',
    presetEditorTitle: 'प्रीसेट संपादक',
    presetNameLabel: 'प्रीसेट का नाम',
    presetDescriptionLabel: 'विवरण',
    applyAndSave: 'लागू करें और सहेजें',
    noNoise: 'कोई शोर नहीं',
    waveSuffix: ' तरंग'
  },
  bn: {
    appName: 'Noise Generator',
    appTagline: 'সহজ, শান্ত, শুধু আপনার পছন্দের শব্দ।',
    install: 'হোম স্ক্রিনে যোগ করুন',
    installHint: 'হোম স্ক্রিনে যোগ করলে দ্রুত চালু হবে।',
    play: 'চালু',
    stop: 'বন্ধ',
    addToHomeScreen: 'হোম স্ক্রিনে যোগ করুন',
    evidenceTitle: 'ব্যাখ্যা ও গবেষণা',
    platformTitle: 'PWA ও প্ল্যাটফর্ম পার্থক্য',
    simpleExplanationTitle: 'সংক্ষিপ্ত ব্যাখ্যা',
    volumeLabel: 'ভলিউম',
    timerLabel: 'টাইমার',
    timerOff: 'বন্ধ',
    installInfo: 'ইনস্টলেশন তথ্য দেখান',
    addHome: 'হোম স্ক্রিনে যোগ করুন',
    aboutBackground: 'ব্যাকগ্রাউন্ড প্লেব্যাক সম্পর্কে',
    noiseType: 'শব্দের ধরণ',
    noisePapers: 'শব্দ গবেষণা পত্র দেখান',
    noiseReferences: 'শব্দ অধ্যয়নের রেফারেন্স',
    beatOn: 'বাইনরাল বিটস চালু',
    beatLabel: 'বিট',
    beatHelp: 'বাইনরাল বিট সহায়তা দেখান',
    beatDesc: 'প্রতিটি কানে সামান্য ভিন্ন সুর পাঠায় যাতে বিট পার্থক্য আরও স্পষ্টভাবে বোঝা যায়।',
    earphoneMode: 'ইয়ারফোন (বাইনরাল)',
    speakerMode: 'স্পিকার (আইসোক্রোনিক)',
    baseFreq: 'বেস ফ্রিকোয়েন্সি',
    currentBand: 'বর্তমান বিট ব্যান্ড',
    footerNote: 'কোন চিকিৎসা দাবি করা হয় না। এটি সাবধানতার সাথে ব্যবহার করুন এবং আপনার প্রেক্ষাপটের সাথে খাপ খাইয়ে নিন।',
    minute: 'মি',
    second: 'সে',
    iosStep1: 'শেয়ার বোতামটি (উপরে তীর সহ বর্গক্ষেত্র) আলতো চাপুন।',
    iosStep2: 'নিচে স্ক্রোল করুন এবং "হোম স্ক্রিনে যোগ করুন" আলতো চাপুন।',
    iosStep3: 'উপরে ডানদিকে "যোগ করুন" আলতো চাপুন।',
    androidStep1: 'ব্রাউজারে তিন-বিন্দু মেনু আলতো চাপুন।',
    androidStep2: '"অ্যাপ ইনস্টল করুন" বা "হোম স্ক্রিনে যোগ করুন" আলতো চাপুন।',
    gotIt: 'বুঝেছি',
    close: 'বন্ধ করুন',
    presetsTitle: 'দ্রুত প্রিসেট',
    resetPreset: 'সেটিংস রিসেট করুন',
    settingsTitle: 'উন্নত সেটিংস',
    advancedSettings: 'উন্নত সেটিংস দেখান',
    noiseOff: 'বন্ধ',
    edit: 'সম্পাদনা',
    resetPresetsDescription: 'দ্রুত প্রিসেট রিসেট করুন',
    presetEditorTitle: 'প্রিসেট সম্পাদক',
    presetNameLabel: 'প্রিসেটের নাম',
    presetDescriptionLabel: 'বিবরণ',
    applyAndSave: 'প্রয়োগ এবং সংরক্ষণ করুন',
    noNoise: 'কোন শব্দ নেই',
    waveSuffix: ' তরঙ্গ'
  },
  pt: {
    appName: 'Noise Generator',
    appTagline: 'Simples e calmo, apenas o som que voce quer ouvir.',
    install: 'Adicionar a tela inicial',
    installHint: 'Adicionar a tela inicial deixa a abertura mais rapida.',
    play: 'Reproduzir',
    stop: 'Parar',
    addToHomeScreen: 'Adicionar a tela inicial',
    evidenceTitle: 'Explicacao e artigos',
    platformTitle: 'PWA e diferencas de plataforma',
    simpleExplanationTitle: 'Explicacao curta',
    volumeLabel: 'Volume',
    timerLabel: 'Temporizador',
    timerOff: 'Desligado',
    installInfo: 'Mostrar info de instalacao',
    addHome: 'Adicionar a tela inicial',
    aboutBackground: 'Sobre reproducao em segundo plano',
    noiseType: 'Tipo de ruido',
    noisePapers: 'Mostrar artigos de ruido',
    noiseReferences: 'Referencias para estudos de ruido',
    beatOn: 'Batidas binaurais ligadas',
    beatLabel: 'Batida',
    beatHelp: 'Mostrar ajuda de batidas binaurais',
    beatDesc: 'Envia tons ligeiramente diferentes para cada ouvido para que a diferenca de batida seja percebeida mais claramente.',
    earphoneMode: 'Fones de ouvido (Binaural)',
    speakerMode: 'Alto-falantes (Isocrônico)',
    baseFreq: 'Frequência base',
    currentBand: 'Banda de batida atual',
    footerNote: 'Nenhuma alegacao medica e feita. Use com cautela e adapte ao seu contexto.',
    minute: 'm',
    second: 's',
    iosStep1: 'Toque no botão Compartilhar (quadrado com seta para cima).',
    iosStep2: 'Role para baixo e toque em "Adicionar à Tela de Início".',
    iosStep3: 'Toque em "Adicionar" no canto superior direito.',
    androidStep1: 'Toque no menu de três pontos no navegador.',
    androidStep2: 'Toque em "Instalar aplicativo" ou "Adicionar à tela inicial".',
    gotIt: 'Entendido',
    close: 'Fechar',
    presetsTitle: 'Predefinições rápidas',
    resetPreset: 'Redefinir configurações',
    settingsTitle: 'Configurações avanzadas',
    advancedSettings: 'Mostrar configurações avanzadas',
    noiseOff: 'Desligado',
    edit: 'Editar',
    resetPresetsDescription: 'Redefinir predefinições rápidas',
    presetEditorTitle: 'Editor de predefinições',
    presetNameLabel: 'Nome da predefinição',
    presetDescriptionLabel: 'Descrição',
    applyAndSave: 'Aplicar e salvar',
    noNoise: 'Sem ruído',
    waveSuffix: ' onda'
  },
  ru: {
    appName: 'Noise Generator',
    appTagline: 'Просто, спокойно, только нужный вам звук.',
    install: 'Добавить на главный экран',
    installHint: 'Добавление на главный экран ускоряет запуск.',
    play: 'Воспроизвести',
    stop: 'Остановить',
    addToHomeScreen: 'Добавить на главный экран',
    evidenceTitle: 'Объяснение и статьи',
    platformTitle: 'PWA и различия платформ',
    simpleExplanationTitle: 'Краткое объяснение',
    volumeLabel: 'Громкость',
    timerLabel: 'Таймер',
    timerOff: 'Выкл',
    installInfo: 'Показать инфо об установке',
    addHome: 'Добавить на главный экран',
    aboutBackground: 'О фоновом воспроизведении',
    noiseType: 'Тип шума',
    noisePapers: 'Показать статьи о шуме',
    noiseReferences: 'Ссылки на исследования шума',
    beatOn: 'Бинауральные ритмы вкл',
    beatLabel: 'Ритм',
    beatHelp: 'Показать справку по ритмам',
    beatDesc: 'Подает слегка разные тона в каждое ухо, чтобы разница ритмов воспринималась четче.',
    earphoneMode: 'Наушники (Бинаурально)',
    speakerMode: 'Динамики (Изохронно)',
    baseFreq: 'Базовая частота',
    currentBand: 'Текущий диапазон ритма',
    footerNote: 'Медицинские заявления не делаются. Используйте с осторожностью и адаптируйте под себя.',
    minute: 'мин',
    second: 'сек',
    iosStep1: 'Нажмите кнопку «Поделиться» (квадрат со стрелкой вверх).',
    iosStep2: 'Прокрутите вниз и нажмите «На экран "Домой"».',
    iosStep3: 'Нажмите «Добавить» в правом верхнем углу.',
    androidStep1: 'Нажмите на меню из трех точек в браузере.',
    androidStep2: 'Нажмите «Установить приложение» или «На экран "Домой"».',
    gotIt: 'Понятно',
    close: 'Закрыть',
    presetsTitle: 'Быстрые пресеты',
    resetPreset: 'Сбросить настройки',
    settingsTitle: 'Расширенные настройки',
    advancedSettings: 'Показать расширенные настройки',
    noiseOff: 'Выкл',
    edit: 'Редактировать',
    resetPresetsDescription: 'Сбросить быстрые пресеты',
    presetEditorTitle: 'Редактор пресетов',
    presetNameLabel: 'Название пресета',
    presetDescriptionLabel: 'Описание',
    applyAndSave: 'Применить и сохранить',
    noNoise: 'Без шума',
    waveSuffix: ' волна'
  },
  yue: {
    appName: 'Noise Generator',
    appTagline: '簡單、寧靜，只播你想聽嘅聲音。',
    install: '加入主畫面',
    installHint: '加入主畫面之後，啟動會更快。',
    play: '播放',
    stop: '停止',
    addToHomeScreen: '加入主畫面',
    evidenceTitle: '說明同論文',
    platformTitle: 'PWA 同平台差異',
    simpleExplanationTitle: '簡短說明',
    volumeLabel: '音量',
    timerLabel: '計時器',
    timerOff: '關閉',
    installInfo: '顯示安裝資訊',
    addHome: '加入主畫面',
    aboutBackground: '關於背景播放',
    noiseType: '噪音類型',
    noisePapers: '顯示噪音論文',
    noiseReferences: '噪音研究參考',
    beatOn: '開啟雙耳節拍',
    beatLabel: '節拍',
    beatHelp: '顯示雙耳節拍說明',
    beatDesc: '向每隻耳仔發送略有不同嘅音調，以便更清晰地感知節拍差異。',
    earphoneMode: '耳機（雙耳）',
    speakerMode: '揚聲器（等時線）',
    baseFreq: '基準頻率',
    currentBand: '當前節拍頻帶',
    footerNote: '唔作醫療聲明。請謹慎使用並適應你嘅環境。',
    minute: '分',
    second: '秒',
    iosStep1: '撳「分享」掣（帶上箭頭嘅方塊）。',
    iosStep2: '向下捲動並撳「加入主畫面」。',
    iosStep3: '撳右上角嘅「加入」。',
    androidStep1: '撳瀏覽器入面個三點選單。',
    androidStep2: '撳「安裝應用程式」或者「加入主畫面」。',
    gotIt: '知道喇',
    close: '關閉',
    presetsTitle: '快速預設',
    resetPreset: '重置設定',
    settingsTitle: '高級設定',
    advancedSettings: '顯示高級設定',
    noiseOff: '關閉',
    edit: '編輯',
    resetPresetsDescription: '重置快速預設',
    presetEditorTitle: '預設編輯器',
    presetNameLabel: '預設名稱',
    presetDescriptionLabel: '描述',
    applyAndSave: '應用並保存',
    noNoise: '無噪音',
    waveSuffix: '波'
  },
  vi: {
    appName: 'Noise Generator',
    appTagline: 'Don gian, yen tinh, chi phat am thanh ban muon nghe.',
    install: 'Them vao man hinh chinh',
    installHint: 'Them vao man hinh chinh giup mo nhanh hon.',
    play: 'Phat',
    stop: 'Dung',
    addToHomeScreen: 'Them vao man hinh chinh',
    evidenceTitle: 'Giai thich va bai bao',
    platformTitle: 'PWA va khac biet nen tang',
    simpleExplanationTitle: 'Giai thich ngan',
    volumeLabel: 'Am luong',
    timerLabel: 'Hen gio',
    timerOff: 'Tat',
    installInfo: 'Hien thi thong tin cai dat',
    addHome: 'Them vao man hinh chinh',
    aboutBackground: 'Ve phat trong nen',
    noiseType: 'Loai tieng on',
    noisePapers: 'Hien thi bai bao ve tieng on',
    noiseReferences: 'Tai lieu tham khao tieng on',
    beatOn: 'Bat nhip binaural',
    beatLabel: 'Nhịp',
    beatHelp: 'Hien tro giup nhip binaural',
    beatDesc: 'Gui cac am thanh hoi khac nhau den moi tai de co the cam nhan su khac biet nhip ro rang hon.',
    earphoneMode: 'Tai nghe (Binaural)',
    speakerMode: 'Loa (Isochronic)',
    baseFreq: 'Tan so co ban',
    currentBand: 'Bang nhip hien tai',
    footerNote: 'Khong co tuyen bo y te nao duoc dua ra. Su dung than trong va phu hop voi boi canh cua ban.',
    minute: 'p',
    second: 'g',
    iosStep1: 'Chạm vào nút Chia sẻ (hình vuông có mũi tên lên).',
    iosStep2: 'Cuộn xuống và chạm vào "Thêm vào màn hình chính".',
    iosStep3: 'Chạm vào "Thêm" ở góc trên bên phải.',
    androidStep1: 'Chạm vào menu ba dấu chấm trong trình duyệt.',
    androidStep2: 'Chạm vào "Cài đặt ứng dụng" hoặc "Thêm vào màn hình chính".',
    gotIt: 'Đã hiểu',
    close: 'Đóng',
    presetsTitle: 'Cài đặt nhanh',
    resetPreset: 'Đặt lại cài đặt',
    settingsTitle: 'Cài đặt nâng cao',
    advancedSettings: 'Hiển thị cài đặt nâng cao',
    noiseOff: 'Tắt',
    edit: 'Chỉnh sửa',
    resetPresetsDescription: 'Đặt lại cài đặt nhanh',
    presetEditorTitle: 'Trình chỉnh sửa cài đặt',
    presetNameLabel: 'Tên cài đặt',
    presetDescriptionLabel: 'Mô tả',
    applyAndSave: 'Áp dụng và lưu',
    noNoise: 'Không có tiếng ồn',
    waveSuffix: ' sóng'
  },
  mr: {
    appName: 'Noise Generator',
    appTagline: 'सोपे, शांत, फक्त तुम्हाला हवे तेच आवाज.',
    install: 'होम स्क्रीनवर जोडा',
    installHint: 'होम स्क्रीनवर जोडल्यास ॲप वेगाने उघडते.',
    play: 'प्ले करा',
    stop: 'थांबवा',
    addToHomeScreen: 'होम स्क्रीनवर जोडा',
    evidenceTitle: 'स्पष्टीकरण आणि शोधनिबंध',
    platformTitle: 'PWA आणि प्लॅटफॉर्ममधील फरक',
    simpleExplanationTitle: 'थोडक्यात स्पष्टीकरण',
    volumeLabel: 'आवाज',
    timerLabel: 'टायमर',
    timerOff: 'बंद',
    installInfo: 'इन्स्टॉलेशन माहिती पहा',
    addHome: 'होम स्क्रीनवर जोडा',
    aboutBackground: 'बॅकग्राउंड प्लेबॅकबद्दल',
    noiseType: 'आवाजाचा प्रकार',
    noisePapers: 'आवाज शोधनिबंध पहा',
    noiseReferences: 'आवाज अभ्यासाचे संदर्भ',
    beatOn: 'बाइनोरल बीट्स सुरू',
    beatLabel: 'बीट',
    beatHelp: 'बाइनोरल बीट मदत पहा',
    beatDesc: 'प्रत्येक कानात थोडे वेगळे टोन पाठवते जेणेकरून बीटमधील फरक अधिक स्पष्टपणे जाणवेल.',
    earphoneMode: 'इअरफोन्स (बाइनोरल)',
    speakerMode: 'स्पीकर (आयसोक्रोनिक)',
    baseFreq: 'बेस फ्रिक्वेन्सी',
    currentBand: 'सध्याचा बीट बँड',
    footerNote: 'कोणताही वैद्यकीय दावा केला जात नाही. काळजीपूर्वक वापरा आणि तुमच्या गरजेनुसार बदला.',
    minute: 'मि',
    second: 'से',
    iosStep1: 'शेअर बटण (वर बाण असलेला चौरस) वर टॅप करा.',
    iosStep2: 'खाली स्क्रोल करा आणि "होम स्क्रीनवर जोडा" वर टॅप करा.',
    iosStep3: 'वर उजवीकडे "जोडा" वर टॅप करा.',
    androidStep1: 'ब्राउझरमधील तीन-बिंदू मेनूवर टॅप करा.',
    androidStep2: '"ॲप इंस्टॉल करा" किंवा "होम स्क्रीनवर जोडा" वर टॅप करा.',
    gotIt: 'समजले',
    close: 'बंद करा',
    presetsTitle: 'त्वरित प्रीसेट्स',
    resetPreset: 'सेटिंग्ज रिसेट करा',
    settingsTitle: 'प्रगत सेटिंग्ज',
    advancedSettings: 'प्रगत सेटिंग्ज पहा',
    noiseOff: 'बंद',
    edit: 'संपादित करा',
    resetPresetsDescription: 'त्वरित प्रीसेट रिसेट करा',
    presetEditorTitle: 'प्रीसेट संपादक',
    presetNameLabel: 'प्रीसेटचे नाव',
    presetDescriptionLabel: 'वर्णन',
    applyAndSave: 'लागू करा आणि जतन करा',
    noNoise: 'आवाज नाही',
    waveSuffix: ' लहरी'
  },
  te: {
    appName: 'Noise Generator',
    appTagline: 'సరళంగా, ప్రశాంతంగా, మీకు కావలసిన శబ్దమే.',
    install: 'హోమ్ స్క్రీన్‌కు చేర్చు',
    installHint: 'హోమ్ స్క్రీన్‌కు చేర్చితే యాప్ త్వరగా తెరుచుకుంటుంది.',
    play: 'ప్లే',
    stop: 'ఆపు',
    addToHomeScreen: 'హోమ్ స్క్రీన్‌కు చేర్చు',
    evidenceTitle: 'వివరణ మరియు పత్రాలు',
    platformTitle: 'PWA మరియు ప్లాట్‌ఫార్మ్ తేడాలు',
    simpleExplanationTitle: 'సంక్షిప్త వివరణ',
    volumeLabel: 'వాల్యూం',
    timerLabel: 'టైమర్',
    timerOff: 'ఆఫ్',
    installInfo: 'ఇన్‌స్టాలేషన్ సమాచారం చూపించు',
    addHome: 'హోమ్ స్క్రీన్‌కు చేర్చు',
    aboutBackground: 'బ్యాక్‌గ్రౌండ్ ప్లేబ్యాక్ గురించి',
    noiseType: 'శబ్దం రకం',
    noisePapers: 'శబ్దం పత్రాలు చూపించు',
    noiseReferences: 'శబ్ద అధ్యయన సూచనలు',
    beatOn: 'బైనరల్ బీట్స్ ఆన్',
    beatLabel: 'బీట్',
    beatHelp: 'బైనరల్ బీట్ సహాయం చూపించు',
    beatDesc: 'ప్రతి చెవికి కొద్దిగా భిన్నమైన టోన్లను పంపుతుంది, తద్వారా బీట్ తేడా మరింత స్పష్టంగా కనిపిస్తుంది.',
    earphoneMode: 'ఇయర్ ఫోన్లు (బైనరల్)',
    speakerMode: 'స్పీకర్లు (ఐసోక్రోనిక్)',
    baseFreq: 'బేస్ ఫ్రీక్వెన్సీ',
    currentBand: 'ప్రస్తుత బీట్ బ్యాండ్',
    footerNote: 'వైద్యపరమైన క్లెయిమ్‌లు ఏవీ చేయబడలేదు. జాగ్రత్తగా ఉపయోగించండి మరియు మీ సందర్భానికి తగినట్లుగా అమర్చుకోండి.',
    minute: 'ని',
    second: 'సె',
    iosStep1: 'షోర్ బటన్ (పైకి బాణం ఉన్న చతురస్రం) నొక్కండి.',
    iosStep2: 'క్రిందికి స్క్రోల్ చేసి "హోమ్ స్క్రీన్‌కు చేర్చు" నొక్కండి.',
    iosStep3: 'పైన కుడివైపున ఉన్న "చేర్చు" నొక్కండి.',
    androidStep1: 'బ్రౌజర్‌లోని మూడు చుక్కల మెనూని నొక్కండి.',
    androidStep2: '"యాప్‌ను ఇన్‌స్టాల్ చేయి" లేదా "హోమ్ స్క్రీన్‌కు చేర్చు" నొక్కండి.',
    gotIt: 'అర్థమైంది',
    close: 'మూసివేయి',
    presetsTitle: 'త్వరిత ప్రీసెట్లు',
    resetPreset: 'సెట్టింగ్‌లను రీసెట్ చేయండి',
    settingsTitle: 'అధునాతన సెట్టింగ్‌లు',
    advancedSettings: 'అధునాతన సెట్టింగ్‌లను చూపించు',
    noiseOff: 'ఆఫ్',
    edit: 'సవరించు',
    resetPresetsDescription: 'త్వరిత ప్రీసెట్లను రీసెట్ చేయండి',
    presetEditorTitle: 'ప్రైసెట్ ఎడిటర్',
    presetNameLabel: 'ప్రీసెట్ పేరు',
    presetDescriptionLabel: 'వివరణ',
    applyAndSave: 'వర్తింపజేసి సేవ్ చేయండి',
    noNoise: 'శబ్దం లేదు',
    waveSuffix: ' తరంగం'
  },
  tr: {
    appName: 'Noise Generator',
    appTagline: 'Basit, sakin, sadece duymak istedigin ses.',
    install: 'Ana ekrana ekle',
    installHint: 'Ana ekrana eklemek daha hizli acilis saglar.',
    play: 'Oynat',
    stop: 'Durdur',
    addToHomeScreen: 'Ana ekrana ekle',
    evidenceTitle: 'Aciklama ve makaleler',
    platformTitle: 'PWA ve platform farklari',
    simpleExplanationTitle: 'Kisa aciklama',
    volumeLabel: 'Ses',
    timerLabel: 'Zamanlayici',
    timerOff: 'Kapali',
    installInfo: 'Kurulum bilgisini goster',
    addHome: 'Ana ekrana ekle',
    aboutBackground: 'Arka plan oynatma hakkinda',
    noiseType: 'Gurultu tipi',
    noisePapers: 'Gurultu makalelerini goster',
    noiseReferences: 'Gurultu calismalari referanslari',
    beatOn: 'Binaural vuruslar acik',
    beatLabel: 'Vuruş',
    beatHelp: 'Binaural vurus yardimini goster',
    beatDesc: 'Vurus farkinin daha net algilanabilmesi icin her kulaga biraz farkli tonlar gonderir.',
    earphoneMode: 'Kulaklıklar (Binaural)',
    speakerMode: 'Hoparlörler (İzokronik)',
    baseFreq: 'Temel frekans',
    currentBand: 'Guncel vurus bandi',
    footerNote: 'Tibbi bir iddiada bulunulmamaktadir. Dikkatli kullanin ve baglaminiza gore uyarlayin.',
    minute: 'dk',
    second: 'sn',
    iosStep1: 'Paylaş düğmesine (yukarı oklu kare) dokunun.',
    iosStep2: 'Aşağı kaydırın ve "Ana Ekrana Ekle"ye dokunun.',
    iosStep3: 'Sağ üstteki "Ekle"ye dokunun.',
    androidStep1: 'Tarayıcıdaki üç nokta menüsüne dokunun.',
    androidStep2: '"Uygulamayı yükle" veya "Ana ekrana ekle"ye dokunun.',
    gotIt: 'Anladım',
    close: 'Kapat',
    presetsTitle: 'Hızlı Hazır Ayarlar',
    resetPreset: 'Ayarları Sıfırla',
    settingsTitle: 'Gelişmiş Ayarlar',
    advancedSettings: 'Gelişmiş ayarları göster',
    noiseOff: 'Kapalı',
    edit: 'Düzenle',
    resetPresetsDescription: 'Hızlı hazır ayarları sıfırla',
    presetEditorTitle: 'Hazır Ayar Düzenleyici',
    presetNameLabel: 'Hazır ayar adı',
    presetDescriptionLabel: 'Açıklama',
    applyAndSave: 'Uygula ve Kaydet',
    noNoise: 'Gürültü yok',
    waveSuffix: ' dalgası'
  },
  ko: {
    appName: 'Noise Generator',
    appTagline: '간단하고 조용하게, 원하는 소리만.',
    install: '홈 화면에 추가',
    installHint: '홈 화면에 추가하면 더 빠르게 실행됩니다.',
    play: '재생',
    stop: '정지',
    addToHomeScreen: '홈 화면에 추가',
    evidenceTitle: '설명과 논문',
    platformTitle: 'PWA 및 플랫폼 차이',
    simpleExplanationTitle: '짧은 설명',
    volumeLabel: '볼륨',
    timerLabel: '타이머',
    timerOff: '끔',
    installInfo: '설치 정보 표시',
    addHome: '홈 화면에 추가',
    aboutBackground: '백그라운드 재생에 대하여',
    noiseType: '노이즈 유형',
    noisePapers: '노이즈 논문 표시',
    noiseReferences: '노이즈 연구 참고 문서',
    beatOn: '바이노럴 비트 켜짐',
    beatLabel: '비트',
    beatHelp: '바이노럴 비트 도움말 표시',
    beatDesc: '양쪽 귀에 약간 다른 주파수를 흘려 차이 주파수를 더 명확하게 느낄 수 있게 하는 기능입니다.',
    earphoneMode: '이어폰 (바이노럴)',
    speakerMode: '스피커 (아이소크로닉)',
    baseFreq: '베이스 주파수',
    currentBand: '현재 비트 밴드',
    footerNote: '의료적 효과를 보장하지 않습니다. 용도에 맞게 주의해서 사용하십시오.',
    minute: '분',
    second: '초',
    iosStep1: '공유 버튼(위쪽 화살표가 있는 사각형)을 누릅니다.',
    iosStep2: '아래로 스크롤하여 \'홈 화면에 추가\'를 누릅니다.',
    iosStep3: '오른쪽 상단의 \'추가\'를 누릅니다.',
    androidStep1: '브라우저에서 점 3개 메뉴를 누릅니다.',
    androidStep2: '\'앱 설치\' 또는 \'홈 화면에 추가\'를 누릅니다.',
    gotIt: '확인',
    close: '닫기',
    presetsTitle: '퀵 프리셋',
    resetPreset: '설정 초기화',
    settingsTitle: '고급 설정',
    advancedSettings: '고급 설정 표시',
    noiseOff: '끔',
    edit: '편집',
    resetPresetsDescription: '퀵 프리셋 초기화',
    presetEditorTitle: '프리셋 편집기',
    presetNameLabel: '프리셋 이름',
    presetDescriptionLabel: '설명',
    applyAndSave: '적용 및 저장',
    noNoise: '노이즈 없음',
    waveSuffix: '파'
  },
  pa: {
    appName: 'Noise Generator',
    appTagline: 'ਸੌਖਾ, ਸ਼ਾਂਤ, ਸਿਰਫ ਉਹੀ ਆਵਾਜ਼ ਜੋ ਤੁਸੀਂ ਸੁਣਨਾ ਚਾਹੋ।',
    install: 'ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜੋ',
    installHint: 'ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜਨ ਨਾਲ ਐਪ ਜਲਦੀ ਖੁਲਦਾ ਹੈ।',
    play: 'ਪਲਾਓ',
    stop: 'ਰੋਕੋ',
    addToHomeScreen: 'ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜੋ',
    evidenceTitle: 'ਵਿਆਖਿਆ ਅਤੇ ਲੇਖ',
    platformTitle: 'PWA ਅਤੇ ਪਲੇਟਫਾਰਮ ਅੰਤਰ',
    simpleExplanationTitle: 'ਛੋਟੀ ਵਿਆਖਿਆ',
    volumeLabel: 'ਆਵਾਜ਼',
    timerLabel: 'ਟਾਈਮਰ',
    timerOff: 'ਬੰਦ',
    installInfo: 'ਇੰਸਟਾਲੇਸ਼ਨ ਜਾਣਕਾਰੀ ਦਿਖਾਓ',
    addHome: 'ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜੋ',
    aboutBackground: 'ਬੈਕਗ੍ਰਾਉਂਡ ਪਲੇਬੈਕ ਬਾਰੇ',
    noiseType: 'ਸ਼ੋਰ ਦੀ ਕਿਸਮ',
    noisePapers: 'ਸ਼ੋਰ ਲੇਖ ਦਿਖਾਓ',
    noiseReferences: 'ਸ਼ੋਰ ਅਧਿਐਨ ਦੇ ਹਵਾਲੇ',
    beatOn: 'ਬਾਇਨੋਰਲ ਬੀਟਸ ਚਾਲੂ',
    beatLabel: 'ਬੀਟ',
    beatHelp: 'ਬਾਇਨੋਰਲ ਬੀਟ ਸਹਾਇਤਾ ਦਿਖਾਓ',
    beatDesc: 'ਹਰੇਕ ਕੰਨ ਵਿੱਚ ਥੋੜੇ ਵੱਖਰੇ ਟੋਨ ਭੇਜਦਾ ਹੈ ਤਾਂ ਜੋ ਬੀਟ ਦੇ ਅੰਤਰ ਨੂੰ ਹੋਰ ਸਪਸ਼ਟ ਰੂਪ ਵਿੱਚ समझਿਆ ਜਾ ਸਕੇ।',
    earphoneMode: 'ਈਅਰਫੋਨ (ਬਾਇਨੋਰਲ)',
    speakerMode: 'ਸਪੀਕਰ (ਆਈਸੋਕ੍ਰੋਨਿਕ)',
    baseFreq: 'ਬੇਸ ਫ੍ਰੀਕੁਐਂਸੀ',
    currentBand: 'ਮੌਜੂਦਾ ਬੀਟ ਬੈਂਡ',
    footerNote: 'ਕੋਈ ਡਾਕਟਰੀ ਦਾਅਵਾ ਨਹੀਂ ਕੀਤਾ ਗਿਆ ਹੈ। ਇਸਦੀ ਸਾਵਧਾਨੀ ਨਾਲ ਵਰਤੋਂ ਕਰੋ ਅਤੇ ਆਪਣੇ ਸੰਦਰਭ ਅਨੁਸਾਰ ਢਾਲੋ।',
    minute: 'ਮਿੰਟ',
    second: 'ਸਕਿੰਟ',
    iosStep1: 'ਸ਼ੇਅਰ ਬਟਨ (ਉੱਪਰ ਤੀਰ ਵਾਲਾ ਵਰਗ) \'ਤੇ ਟੈਪ ਕਰੋ।',
    iosStep2: 'ਹੇਠਾਂ ਸਕ੍ਰੋਲ ਕਰੋ ਅਤੇ "ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜੋ" ਤੇ ਟੈਪ ਕਰੋ।',
    iosStep3: 'ਉੱਪਰ ਸੱਜੇ ਪਾਸੇ "जोੜੋ" ਤੇ ਟੈਪ ਕਰੋ।',
    androidStep1: 'ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਤਿੰਨ-ਬਿੰਦੂ ਮੀਨੂ \'ਤੇ ਟੈਪ ਕਰੋ।',
    androidStep2: '"ਐਪ ਇੰਸਟਾਲ ਕਰੋ" ਜਾਂ "ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਜੋੜੋ" ਤੇ ਟੈਪ ਕਰੋ।',
    gotIt: 'ਸਮਝ ਗਏ',
    close: 'ਬੰਦ ਕਰੋ',
    presetsTitle: 'ਤੁਰੰਤ ਪ੍ਰੀਸੈਟਸ',
    resetPreset: 'ਸੈਟਿੰਗਾਂ ਰੀਸੈਟ ਕਰੋ',
    settingsTitle: 'ਉੱਨਤ ਸੈਟਿੰਗਾਂ',
    advancedSettings: 'ਉੱਨਤ ਸੈਟਿੰਗਾਂ ਦਿਖਾਓ',
    noiseOff: 'ਬੰਦ',
    edit: 'ਸੰਪਾਦਿਤ ਕਰੋ',
    resetPresetsDescription: 'ਤੁਰੰਤ ਪ੍ਰੀਸੈਟਸ ਰੀਸੈਟ ਕਰੋ',
    presetEditorTitle: 'ਪ੍ਰੀਸੈਟ ਸੰਪਾਦਕ',
    presetNameLabel: 'ਪ੍ਰੀਸੈਟ ਦਾ ਨਾਮ',
    presetDescriptionLabel: 'ਵੇਰਵਾ',
    applyAndSave: 'ਲਾਗੂ ਕਰੋ ਅਤੇ ਸੁਰੱਖਿਅਤ ਕਰੋ',
    noNoise: 'ਕੋਈ ਸ਼ੋਰ ਨਹੀਂ',
    waveSuffix: ' ਲਹਿਰ'
  },
  ta: {
    appName: 'Noise Generator',
    appTagline: 'எளிதாக, அமைதியாக, உங்களுக்கு வேண்டிய ஒலி மட்டும்.',
    install: 'முதற்பக்கத்தில் சேர்க்க',
    installHint: 'முதற்பக்கத்தில் சேர்த்தால் விரைவாக திறக்கும்.',
    play: 'இயக்கு',
    stop: 'நிறுத்து',
    addToHomeScreen: 'முதற்பக்கத்தில் சேர்க்க',
    evidenceTitle: 'விளக்கம் மற்றும் ஆய்வுகள்',
    platformTitle: 'PWA மற்றும் தளம் வேறுபாடுகள்',
    simpleExplanationTitle: 'சுருக்கமான விளக்கம்',
    volumeLabel: 'ஒலி அளவு',
    timerLabel: 'டைமர்',
    timerOff: 'ஆஃப்',
    installInfo: 'நிறுவல் தகவலைக் காட்டு',
    addHome: 'முதற்பக்கத்தில் சேர்க்க',
    aboutBackground: 'பின்னணி இயக்கம் பற்றி',
    noiseType: 'ஒலி வகை',
    noisePapers: 'ஒலி ஆய்வுகளைக் காட்டு',
    noiseReferences: 'ஒலி ஆய்வுகளின் குறிப்புகள்',
    beatOn: 'பைனரல் பீட்ஸ் ஆன்',
    beatLabel: 'பீட்',
    beatHelp: 'பைனரல் பீட் உதவியைக் காட்டு',
    beatDesc: 'ஒவ்வொரு காதுக்கும் சற்று வித்தியாசமான ஒலிகளை அனுப்புகிறது, இதனால் பீட் வித்தியாசத்தை இன்னும் தெளிவாக உணர முடியும்.',
    earphoneMode: 'இயர்போன்கள் (பைனரல்)',
    speakerMode: 'ஸ்பீக்கர்கள் (ஐசோக்ரோனிக்)',
    baseFreq: 'அடிப்படை அதிர்வெண்',
    currentBand: 'தற்போதைய பீட் பேண்ட்',
    footerNote: 'மருத்துவ ரீதியான உரிமைகோரல்கள் எதுவும் செய்யப்படவில்லை. எச்சரிக்கையுடன் பயன்படுத்தவும்.',
    minute: 'நி',
    second: 'வி',
    iosStep1: 'பகிர் பொத்தானைத் (மேல் அம்புக்குறியுடன் கூடிய சதுரம்) தட்டவும்.',
    iosStep2: 'கீழே உருட்டி "முதற்பக்கத்தில் சேர்க்க" என்பதைத் தட்டவும்.',
    iosStep3: 'மேல் வலதுபுறத்தில் உள்ள "சேர்" என்பதைத் தட்டவும்.',
    androidStep1: 'உலாவியில் உள்ள மூன்று புள்ளி மெனுவைத் தட்டவும்.',
    androidStep2: '"பயன்பாட்டை நிறுவு" அல்லது "முதற்பக்கத்தில் சேர்க்க" என்பதைத் தட்டவும்.',
    gotIt: 'புரிந்தது',
    close: 'மூடு',
    presetsTitle: 'விரைவான முன்னமைவுகள்',
    resetPreset: 'அமைப்புகளை மீட்டமை',
    settingsTitle: 'மேம்பட்ட அமைப்புகள்',
    advancedSettings: 'மேம்பட்ட அமைப்புகளைக் காட்டு',
    noiseOff: 'ஆஃப்',
    edit: 'திருத்து',
    resetPresetsDescription: 'விரைவான முன்னமைவுகளை மீட்டமை',
    presetEditorTitle: 'முன்னமைவு எடிட்டர்',
    presetNameLabel: 'முன்னமைவு பெயர்',
    presetDescriptionLabel: 'விளக்கம்',
    applyAndSave: 'பயன்பாடுத்தி சேமி',
    noNoise: 'ஒலி இல்லை',
    waveSuffix: ' அலை'
  },
  jv: {
    appName: 'Noise Generator',
    appTagline: 'Prasaja lan anteng, mung swara sing arep kok rungokke.',
    install: 'Tambahna menyang layar ngarep',
    installHint: 'Yen ditambah menyang layar ngarep, mbukak app luwih cepet.',
    play: 'Puter',
    stop: 'Mandheg',
    addToHomeScreen: 'Tambahna menyang layar ngarep',
    evidenceTitle: 'Panjelasan lan artikel',
    platformTitle: 'PWA lan bedane platform',
    simpleExplanationTitle: 'Panjelasan cekak',
    volumeLabel: 'Volume',
    timerLabel: 'Timer',
    timerOff: 'Mati',
    installInfo: 'Tampilake info instalasi',
    addHome: 'Tambah menyang layar ngarep',
    aboutBackground: 'Babagan puter ing mburi',
    noiseType: 'Tipe swara',
    noisePapers: 'Tampilake artikel swara',
    noiseReferences: 'Referensi kanggo studi swara',
    beatOn: 'Ketukan binaural urip',
    beatLabel: 'Ketukan',
    beatHelp: 'Tampilake pitulung ketukan binaural',
    beatDesc: 'Ngirim nada sing rada beda menyang saben kuping supaya bedane ketukan bisa dirasakake luwih cetha.',
    earphoneMode: 'Earphone (Binaural)',
    speakerMode: 'Speaker (Isochronic)',
    baseFreq: 'Frekuensi dasar',
    currentBand: 'Band ketukan saiki',
    footerNote: 'Ora ana klaim medis. Gunakake kanthi teliti lan cocogake karo konteksmu.',
    minute: 'm',
    second: 's',
    iosStep1: 'Tutul tombol Dum (kothak nganggo panah munggah).',
    iosStep2: 'Gulung mudhun lan tutul "Tambahna menyang layar ngarep".',
    iosStep3: 'Tutul "Tambah" ing sisih tengen ndhuwur.',
    androidStep1: 'Tutul menu telu titik im browser.',
    androidStep2: 'Tutul "Pasang aplikasi" utawa "Tambahna menyang layar ngarep".',
    gotIt: 'Ngerti',
    close: 'Tutup',
    presetsTitle: 'Prasetel Cepet',
    resetPreset: 'Reset Setelan',
    settingsTitle: 'Setelan Lanjut',
    advancedSettings: 'Tampilake setelan lanjut',
    noiseOff: 'Mati',
    edit: 'Sunting',
    resetPresetsDescription: 'Reset prasetel cepet',
    presetEditorTitle: 'Editor prasetel',
    presetNameLabel: 'Jeneng prasetel',
    presetDescriptionLabel: 'Katrangan',
    applyAndSave: 'Trapake lan simpen',
    noNoise: 'Ora ana swara',
    waveSuffix: ' gelombang'
  },
  it: {
    appName: 'Noise Generator',
    appTagline: 'Semplice e tranquillo, solo il suono che vuoi ascoltare.',
    install: 'Aggiungi alla schermata Home',
    installHint: 'Aggiungendola alla Home, si avvia piu rapidamente.',
    play: 'Riproduci',
    stop: 'Ferma',
    addToHomeScreen: 'Aggiungi alla schermata Home',
    evidenceTitle: 'Spiegazione e studi',
    platformTitle: 'PWA e differenze di piattaforma',
    simpleExplanationTitle: 'Spiegazione breve',
    volumeLabel: 'Volume',
    timerLabel: 'Timer',
    timerOff: 'Off',
    installInfo: 'Mostra info installazione',
    addHome: 'Aggiungi alla schermata iniziale',
    aboutBackground: 'Riproduzione in background',
    noiseType: 'Tipo di rumore',
    noisePapers: 'Mostra studi sul rumore',
    noiseReferences: 'Riferimenti per studi sul rumore',
    beatOn: 'Battiti binaurali attivi',
    beatLabel: 'Battito',
    beatHelp: 'Mostra aiuto battiti binaurali',
    beatDesc: 'Invia toni leggermente diversi a ciascun orecchio in modo che la differenza di battito sia percepita piu chiaramente.',
    earphoneMode: 'Auricolari (Binaurale)',
    speakerMode: 'Altoparlanti (Isocronico)',
    baseFreq: 'Frequenza base',
    currentBand: 'Banda di battito attuale',
    footerNote: 'Non si effettuano affermazioni mediche. Usalo con cautela e adattalo al tuo contesto.',
    minute: 'm',
    second: 's',
    iosStep1: 'Tocca il pulsante Condividi (quadrato con freccia verso l\'alto).',
    iosStep2: 'Scorri verso il basso e tocca "Aggiungi alla schermata Home".',
    iosStep3: 'Tocca "Aggiungi" in alto a destra.',
    androidStep1: 'Tocca il menu con i tre puntini nel browser.',
    androidStep2: 'Tocca "Installa app" o "Aggiungi alla schermata Home".',
    gotIt: 'Ho capito',
    close: 'Chiudi',
    presetsTitle: 'Preset rapidi',
    resetPreset: 'Ripristina impostazioni',
    settingsTitle: 'Impostazioni avanzate',
    advancedSettings: 'Mostra impostazioni avanzate',
    noiseOff: 'Off',
    edit: 'Modifica',
    resetPresetsDescription: 'Ripristina preset rapidi',
    presetEditorTitle: 'Editor dei preset',
    presetNameLabel: 'Nome del preset',
    presetDescriptionLabel: 'Descrizione',
    applyAndSave: 'Applica e salva',
    noNoise: 'Nessun rumore',
    waveSuffix: ' onda'
  },
  fr: {
    appName: 'Noise Generator',
    appTagline: 'Simple et calme, uniquement le son que vous voulez.',
    install: 'Ajouter a l ecran d accueil',
    installHint: 'L ajout a l ecran d accueil accelere le lancement.',
    play: 'Lire',
    stop: 'Arreter',
    addToHomeScreen: 'Ajouter a l ecran d accueil',
    evidenceTitle: 'Explication et etudes',
    platformTitle: 'PWA et differences de plateforme',
    simpleExplanationTitle: 'Explication courte',
    volumeLabel: 'Volume',
    timerLabel: 'Minuteur',
    timerOff: 'Off',
    installInfo: 'Afficher les infos d installation',
    addHome: 'Ajouter a l ecran d accueil',
    aboutBackground: 'A propos de la lecture en arriere-plan',
    noiseType: 'Type de bruit',
    noisePapers: 'Afficher les etudes sur le bruit',
    noiseReferences: 'References pour les etudes sur le bruit',
    beatOn: 'Battements binauraux actifs',
    beatLabel: 'Battement',
    beatHelp: 'Afficher l aide sur les battements',
    beatDesc: 'Envoie des sons legerement differents a chaque oreille pour que la difference de battement soit percue plus clairement.',
    earphoneMode: 'Écouteurs (Binaural)',
    speakerMode: 'Haut-parleurs (Isochrone)',
    baseFreq: 'Frequence de base',
    currentBand: 'Bande de battement actuelle',
    footerNote: 'Aucune reclamation medicale n est faite. Utilisez-le avec prudence et adaptez-le a votre contexte.',
    minute: 'm',
    second: 's',
    iosStep1: 'Appuyez sur le bouton Partager (carré avec une flèche vers le haut).',
    iosStep2: 'Faites défiler vers le bas et appuyez sur « Sur l\'écran d\'accueil ».',
    iosStep3: 'Appuyez sur « Ajouter » en haut à droite.',
    androidStep1: 'Appuyez sur le menu à trois points dans le navigateur.',
    androidStep2: 'Appuyez sur « Installer l\'application » ou « Sur l\'écran d\'accueil ».',
    gotIt: 'J\'ai compris',
    close: 'Fermer',
    presetsTitle: 'Préréglages rapides',
    resetPreset: 'Réinitialiser les paramètres',
    settingsTitle: 'Paramètres avancés',
    advancedSettings: 'Afficher les paramètres avancés',
    noiseOff: 'Désactivé',
    edit: 'Modifier',
    resetPresetsDescription: 'Réinitialiser les préréglages',
    presetEditorTitle: 'Éditeur de préréglages',
    presetNameLabel: 'Nom du préréglage',
    presetDescriptionLabel: 'Description',
    applyAndSave: 'Appliquer et enregistrer',
    noNoise: 'Pas de bruit',
    waveSuffix: ' onde'
  },
  de: {
    appName: 'Noise Generator',
    appTagline: 'Einfach und ruhig, nur der Klang, den du horen willst.',
    install: 'Zum Startbildschirm hinzufugen',
    installHint: 'Mit Startbildschirm startet die App schneller.',
    play: 'Abspielen',
    stop: 'Stoppen',
    addToHomeScreen: 'Zum Startbildschirm hinzufugen',
    evidenceTitle: 'Erklarung und Studien',
    platformTitle: 'PWA und Plattformunterschiede',
    simpleExplanationTitle: 'Kurze Erklarung',
    volumeLabel: 'Lautstarke',
    timerLabel: 'Timer',
    timerOff: 'Aus',
    installInfo: 'Installationsinfo anzeigen',
    addHome: 'Zum Startbildschirm hinzufugen',
    aboutBackground: 'Uber Hintergrundwiedergabe',
    noiseType: 'Rauschtyp',
    noisePapers: 'Rauschstudien anzeigen',
    noiseReferences: 'Referenzen fur Rauschstudien',
    beatOn: 'Binaurale Beats an',
    beatLabel: 'Beat',
    beatHelp: 'Hilfe zu binauralen Beats',
    beatDesc: 'Sendet leicht unterschiedliche Tone an jedes Ohr, damit der Beat-Unterschied deutlicher wahrgenommen werden kann.',
    earphoneMode: 'Kopfhörer (Binaural)',
    speakerMode: 'Lautsprecher (Isochron)',
    baseFreq: 'Basisfrequenz',
    currentBand: 'Aktuelles Beat-Band',
    footerNote: 'Es werden keine medizinischen Anspruche erhoben. Vorsichtig verwenden und an den Kontext anpassen.',
    minute: 'm',
    second: 's',
    iosStep1: 'Tippen Sie auf die Teilen-Schaltfläche (Quadrat mit Pfeil nach oben).',
    iosStep2: 'Scrollen Sie nach unten und tippen Sie auf „Zum Home-Bildschirm“.',
    iosStep3: 'Tippen Sie oben rechts auf „Hinzufügen“.',
    androidStep1: 'Tippen im Browser auf das Drei-Punkte-Menü.',
    androidStep2: 'Tippen auf „App installieren“ oder „Zum Home-Bildschirm hinzufügen“.',
    gotIt: 'Verstanden',
    close: 'Schließen',
    presetsTitle: 'Schnell-Presets',
    resetPreset: 'Einstellungen zurücksetzen',
    settingsTitle: 'Erweiterte Einstellungen',
    advancedSettings: 'Erweiterte Einstellungen anzeigen',
    noiseOff: 'Aus',
    edit: 'Bearbeiten',
    resetPresetsDescription: 'Schnell-Presets zurücksetzen',
    presetEditorTitle: 'Preset-Editor',
    presetNameLabel: 'Preset-Name',
    presetDescriptionLabel: 'Beschreibung',
    applyAndSave: 'Übernehmen und speichern',
    noNoise: 'Kein Rauschen',
    waveSuffix: ' Welle'
  },
  id: {
    appName: 'Noise Generator',
    appTagline: 'Sederhana dan tenang, hanya suara yang ingin kamu dengar.',
    install: 'Tambahkan ke layar utama',
    installHint: 'Menambahkan ke layar utama membuat aplikasi lebih cepat dibuka.',
    play: 'Putar',
    stop: 'Hentikan',
    addToHomeScreen: 'Tambahkan ke layar utama',
    evidenceTitle: 'Penjelasan dan studi',
    platformTitle: 'PWA dan perbedaan platform',
    simpleExplanationTitle: 'Penjelasan singkat',
    volumeLabel: 'Volume',
    timerLabel: 'Timer',
    timerOff: 'Mati',
    installInfo: 'Tampilkan info instalasi',
    addHome: 'Tambahkan ke layar utama',
    aboutBackground: 'Tentang pemutaran latar belakang',
    noiseType: 'Tipe kebisingan',
    noisePapers: 'Tampilkan studi kebisingan',
    noiseReferences: 'Referensi untuk studi kebisingan',
    beatOn: 'Ketukan binaural aktif',
    beatLabel: 'Ketukan',
    beatHelp: 'Tampilkan bantuan ketukan binaural',
    beatDesc: 'Mengirimkan nada yang sedikit berbeda ke setiap telinga sehingga perbedaan ketukan dapat dirasakan lebih jelas.',
    earphoneMode: 'Earphone (Binaural)',
    speakerMode: 'Speaker (Isokronik)',
    baseFreq: 'Frekuensi dasar',
    currentBand: 'Pita ketukan saat ini',
    footerNote: 'Tidak ada klaim medis yang dibuat. Gunakan dengan hatihati dan sesuaikan dengan konteks Anda.',
    minute: 'm',
    second: 's',
    iosStep1: 'Ketuk tombol Bagikan (persegi dengan panah ke atas).',
    iosStep2: 'Gulir ke bawah dan ketuk "Tambahkan ke Layar Utama".',
    iosStep3: 'Ketuk "Tambah" di kanan atas.',
    androidStep1: 'Ketuk menu tiga titik di browser.',
    androidStep2: 'Ketuk "Instal aplikasi" utawa "Tambahkan ke layar utama".',
    gotIt: 'Mengerti',
    close: 'Tutup',
    presetsTitle: 'Preset Cepat',
    resetPreset: 'Reset Pengaturan',
    settingsTitle: 'Pengaturan Lanjutan',
    advancedSettings: 'Tampilkan pengaturan lanjutan',
    noiseOff: 'Mati',
    edit: 'Edit',
    resetPresetsDescription: 'Reset preset cepat',
    presetEditorTitle: 'Editor Preset',
    presetNameLabel: 'Nama preset',
    presetDescriptionLabel: 'Deskripsi',
    applyAndSave: 'Terapkan dan Simpan',
    noNoise: 'Tanpa suara',
    waveSuffix: ' gelombang'
  }
};

export function resolveLocalizedText(text: LocalizedText, locale: Locale): string {
  return text[locale] ?? text.en ?? text.ja ?? '';
}

function resolveLocalizedList(list: LocalizedList, locale: Locale): string[] {
  return list[locale] ?? list.en ?? list.ja ?? [];
}

export const noiseTypes: Array<{
  key: NoiseType;
  label: LocalizedText;
  short: LocalizedText;
}> = [
  { 
    key: 'white', 
    label: { 
      ja: 'ホワイト', en: 'White', 'zh-Hans': '白噪音', es: 'Blanco', ko: '화이트', fr: 'Blanc', de: 'Weiß',
      hi: 'सफ़ेद', bn: 'সাদা', pt: 'Branco', ru: 'Белый', yue: '白噪音', vi: 'Trắng', mr: 'पांढरा', te: 'తెలుపు', tr: 'Beyaz', pa: 'ਚਿੱਟਾ', ta: 'வெள்ளை', jv: 'Putih', it: 'Bianco', id: 'Putih'
    }, 
    short: { 
      ja: '環境音を目立ちにくくして、作業や休憩の切り替えに使われることがあります。', 
      en: 'Often used to mask background sounds and support task or rest transitions.',
      'zh-Hans': '通常用于遮蔽背景噪音，支持工作或休息的切换。',
      es: 'A menudo se usa para enmascarar sonidos de fondo y apoyar transiciones de tareas.',
      ko: '주변 소음을 차단하고 작업이나 휴식의 전환을 돕는 데 사용됩니다.',
      fr: 'Souvent utilisé pour masquer les bruits de fond et faciliter les transitions.',
      de: 'Wird oft verwendet, um Hintergrundgeräusche zu maskieren.',
      hi: 'अक्सर पृष्ठभूमि की आवाज़ों को छिपाने और कार्य या आराम के संक्रमण का समर्थन करने के लिए उपयोग किया जाता है।',
      bn: 'প্রায়শই পটভূমির শব্দ মাস্ক করতে এবং কাজ বা বিশ্রামের ট্রানজিশন সমর্থন করতে ব্যবহৃত হয়।',
      pt: 'Frequentemente usado para mascarar sons de fundo e apoiar transições de tarefas ou descanso.',
      ru: 'Часто используется для маскировки фоновых звуков и поддержки переходов между задачами или отдыхом.',
      yue: '通常用於遮蔽背景噪音，支持工作或休息嘅切換。',
      vi: 'Thường được sử dụng để che bớt âm thanh nền và hỗ trợ chuyển đổi công việc hoặc nghỉ ngơi.',
      mr: 'बऱ्याचदा पार्श्वभूमीचे आवाज मास्क करण्यासाठी आणि कार्य किंवा विश्रांती संक्रमणास समर्थन देण्यासाठी वापरले जाते.',
      te: 'తరచుగా నేపథ్య శబ్దాలను దాచడానికి మరియు పని లేదా విశ్రాంతి పరివర్తనలకు మద్దతు ఇవ్వడానికి ఉపయోగిస్తారు.',
      tr: 'Genellikle arka plan seslerini maskelemek ve görev veya dinlenme geçişlerini desteklemek için kullanılır.',
      pa: 'ਅਕਸਰ ਪਿਛੋਕੜ ਦੀਆਂ आਵਾਜ਼ਾਂ ਨੂੰ ਲੁਕਾਉਣ ਅਤੇ ਕੰਮ ਜਾਂ ਆਰਾਮ ਦੇ ਸੰਕਰਮਣ ਦਾ ਸਮਰਥਨ ਕਰਨ ਲਈ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ।',
      ta: 'பின்னணி ஒலிகளை மறைக்கவும், வேலை அல்லது ஓய்வு மாற்றங்களுக்கு ஆதரவளிக்கவும் பெரும்பாலும் பயன்படுத்தப்படுகிறது.',
      jv: 'Asring digunake kanggo nutupi swara latar mburi lan ndhukung transisi tugas utawa istirahat.',
      it: 'Spesso utilizzato per mascherare i suoni di sottofondo e supportare le transizioni tra attività o riposo.',
      id: 'Sering digunakan untuk menyamarkan suara latar belakang dan mendukung transisi tugas atau istirahat.'
    } 
  },
  { 
    key: 'pink', 
    label: { 
      ja: 'ピンク', en: 'Pink', 'zh-Hans': '粉红噪音', es: 'Rosa', ko: '핑크', fr: 'Rose', de: 'Rosa',
      hi: 'गुलाबी', bn: 'গোলাপী', pt: 'Rosa', ru: 'Розовый', yue: '粉紅噪音', vi: 'Hồng', mr: 'गुलाबी', te: 'గులాబీ', tr: 'Pembe', pa: 'ਗੁਲਾਬੀ', ta: 'இளஞ்சிவப்பு', jv: 'Abang enom', it: 'Rosa', id: 'Merah muda'
    }, 
    short: { 
      ja: '就寝前に落ち着きやすいと感じる人がいます。睡眠への効果は研究でも個人差があります。', 
      en: 'Some people find it easier to settle before sleep. Sleep effects vary across studies.',
      'zh-Hans': '有些人觉得睡前更容易安静。睡眠效果在研究中因人而异。',
      es: 'A algunas personas les resulta más fácil calmarse antes de dormir.',
      ko: '취침 전에 마음을 진정시키는 데 도움이 될 수 있습니다. 수면 효과는 개인차가 있습니다.',
      fr: 'Certaines personnes le trouvent apaisant avant de dormir.',
      de: 'Manche finden es vor dem Schlafengehen beruhigend.',
      hi: 'कुछ लोगों को सोने से पहले शांत होना आसान लगता है। नींद पर এর प्रभाव अध्ययनों में भिन्न होते हैं।',
      bn: 'কিছু মানুষ ঘুমানোর আগে শান্ত হওয়া সহজ মনে করেন। ঘুমের উপর এর প্রভাব বিভিন্ন গবেষণায় ভিন্ন ভিন্ন হয়।',
      pt: 'Algumas pessoas acham mais fácil relaxar antes de dormir. Os efeitos no sono variam entre los estudos.',
      ru: 'Некоторым людям легче успокоиться перед сном. Эффект на сон варьируется в разных исследованиях.',
      yue: '有啲人覺得睡前更容易安靜。睡眠效果喺研究中因人而異。',
      vi: 'Một số người cảm thấy dễ dàng bình tĩnh hơn trước khi ngủ. Hiệu quả giấc ngủ thay đổi tùy theo nghiên cứu.',
      mr: 'काही लोकांना झोपण्यापूर्वी शांत होणे सोपे वाटते. झोपेवर होणारे परिणाम अभ्यासानुसार बदलतात.',
      te: 'కొంతమంది నిద్రపోయే ముందు ప్రశాంతంగా ఉండటం సులభం అని భావిస్తారు. నిద్రపై దీని ప్రభావాలు అధ్యయనాలలో మారుతుంటాయి.',
      tr: 'Bazı insanlar uykudan önce sakinleşmeyi daha kolay bulur. Uyku etkileri çalışmalar arasında farklılık gösterir.',
      pa: 'ਕੁਝ ਲੋਕਾਂ ਨੂੰ ਸੌਣ ਤੋਂ ਪਹਿਲਾਂ ਸ਼ਾਂਤ ਹੋਣਾ ਸੌਖਾ ਲੱਗਦਾ ਹੈ। ਨੀਂਦ \'ਤੇ ਇਸਦੇ ਪ੍ਰਭਾਵ ਵੱਖ-ਵੱਖ ਅਧਿਐਨਾਂ ਵਿੱਚ ਵੱਖਰੇ ਹੁੰਦੇ ਹਨ।',
      ta: 'சிலர் தூங்குவதற்கு முன் அமைதியடைவது எளிது என்று கருதுகின்றனர். தூக்கத்தின் மீதான இதன் விளைவுகள் ஆய்வுகளில் மாறுபடும்.',
      jv: 'Sawetara wong ngrasa luwih gampang tenang sadurunge turu. Efek turu beda-beda ing saben panaliten.',
      it: 'Alcune persone trovano più facile calmarsi prima di dormire. Gli effetti sul sonno variano a seconda degli studi.',
      id: 'Beberapa orang merasa lebih mudah untuk tenang sebelum tidur. Efek tidur bervariasi di berbagai penelitian.'
    } 
  },
  { 
    key: 'brown', 
    label: { 
      ja: 'ブラウン', en: 'Brown', 'zh-Hans': '褐噪音', es: 'Marrón', ko: '브라운', fr: 'Brun', de: 'Braun',
      hi: 'भूरा', bn: 'बादামী', pt: 'Castanho', ru: 'Коричневый', yue: '褐噪音', vi: 'Nâu', mr: 'तपकिरी', te: 'గోధుమ', tr: 'Kahverengi', pa: 'ਭੂਰਾ', ta: 'பழுப்பு', jv: 'Coklat', it: 'Marrone', id: 'Cokelat'
    }, 
    short: { 
      ja: '低めで包まれる感覚があり、リラックス目的で選ばれることがあります。', 
      en: 'Its deeper tone can feel enveloping, so some listeners choose it for relaxation.',
      'zh-Hans': '低沉的包围感，常被用于放松目的。',
      es: 'Su tono más profundo puede sentirse envolvente, ideal para la relajación.',
      ko: '낮은 톤으로 감싸이는 느낌이 있어 휴식을 위해 선택되기도 합니다.',
      fr: 'Son ton plus profond peut sembler enveloppant, idéal pour la relaxation.',
      de: 'Sein tieferer Ton kann sich einhüllend anfühlen, ideal zur Entspannung.',
      hi: 'इसकी गहरी ध्वनि घेरने वाली महसूस हो सकती है, इसलिए कुछ सुनने वाले इसे विश्राम के लिए चुनते हैं।',
      bn: 'এর গভীর সুর আপনাকে ঘিরে রাখার অনুভূতি দিতে পারে, তাই কিছু শ্রোতা এটি বিশ্রামের জন্য বেছে নেন।',
      pt: 'Seu tom mais profundo pode parecer envolvente, por isso alguns ouvintes o escolhem para relaxar.',
      ru: 'Его более глубокий тон может казаться обволакивающим, поэтому некоторые слушатели выбирают его для расслабления.',
      yue: '低沉嘅包圍感，常用於放鬆目的。',
      vi: 'Tông màu sâu hơn của nó có thể tạo cảm giác bao bọc, vì vậy một số người nghe chọn it để thư giãn.',
      mr: 'याचा सखोल सूर वेढून घेणारा वाटू शकतो, म्हणून काही श्रोते विश्रांतीसाठी याची निवड करतात.',
      te: 'దీని లోతైన టోన్ ఆవరించినట్లు అనిపిస్తుంది, కాబట్టి కొంతమంది శ్రోతలు విశ్రాంతి కోసం దీనిని ఎంచుకుంటారు.',
      tr: 'Daha derin tonu çevreleyici hissettirebilir, bu nedenle bazı dinleyiciler bunu rahatlama için seçer.',
      pa: 'ਇਸਦਾ ਡੂੰਘਾ ਸੁਰ ਘੇਰਨ ਵਾਲਾ ਮਹਿਸੂਸ ਹੋ ਸਕਦਾ ਹੈ, ਇਸ ਲਈ ਕੁਝ ਸੁਣਨ ਵਾਲੇ ਇਸਨੂੰ ਆਰਾਮ ਲਈ ਚੁਣਦੇ ਹਨ।',
      ta: 'இதன் ஆழமான ஒலி சூழ்ந்திருப்பது போன்ற உணர்வைத் தரும், எனவே சில கேட்பவர்கள் இதை ஓய்வெடுக்கத் தேர்வு செய்கிறார்கள்।',
      jv: 'Nada sing luwih jero bisa krasa ngrangkul, mula sawetara wong milih iki kanggo relaksasi.',
      it: 'Il suo tono più profondo può sembrare avvolgente, quindi alcuni ascoltatori lo scelgono per il rilassamento.',
      id: 'Nadanya yang lebih dalam bisa terasa menyelimuti, sehingga beberapa pendengar memilihnya untuk relaksasi.'
    } 
  },
  { 
    key: 'blue', 
    label: { 
      ja: 'ブルー', en: 'Blue', 'zh-Hans': '蓝噪音', es: 'Azul', ko: '블루', fr: 'Bleu', de: 'Blau',
      hi: 'नीला', bn: 'নীল', pt: 'Azul', ru: 'Голубой', yue: '藍噪音', vi: 'Xanh dương', mr: 'निळा', te: 'నీలం', tr: 'Mavi', pa: 'ਨੀਲਾ', ta: 'நீலம்', jv: 'Biru', it: 'Blu', id: 'Biru'
    }, 
    short: { 
      ja: '気分を切り替えたい場面で、短時間の集中スイッチとして使う人もいます。', 
      en: 'Sometimes used as a short focus reset when people want a quick mental shift.',
      'zh-Hans': '在需要转换心情时，有人将其作为短时间集中的开关。',
      es: 'A veces se usa como un breve reinicio de enfoque para un cambio mental rápido.',
      ko: '기분 전환이 필요한 상황에서 단시간 집중을 위한 스위치로 사용되기도 합니다.',
      fr: 'Parfois utilisé pour réinitialiser la concentration rapidement.',
      de: 'Wird manchmal für einen kurzen Fokus-Reset verwendet.',
      hi: 'कभी-कभी एक संक्षिप्त ध्यान रीसेट के रूप में उपयोग किया जाता है जब लोग एक त्वरित मानसिक बदलाव चाहते हैं।',
      bn: 'কখনও কখনও একটি সংক্ষিপ্ত ফোকাস রিসেট হিসাবে ব্যবহৃত হয় যখন লোকেরা দ্রুত মানসিক পরিবর্তন চান।',
      pt: 'Às vezes usado como um breve reinício de foco quando as pessoas querem uma mudança mental rápida.',
      ru: 'Иногда используется как кратковременная перезагрузка внимания, когда требуется быстрая смена психического состояния.',
      yue: '喺需要轉換心情時，有人將佢作為短時間集中嘅開關。',
      vi: 'Đôi khi được sử dụng như một lần đặt lại sự tập trung ngắn khi mọi người muốn có một sự thay đổi tinh thần nhanh chóng.',
      mr: 'जेव्हा लोकांना त्वरित मानसिक बदल हवा असतो तेव्हा कधीकधी संक्षिप्त फोकस रीसेट म्हणून वापरले जाते.',
      te: 'ప్రజలు త్వరిత మానసిక మార్పును కోరుకున్నప్పుడు కొన్నిసార్లు చిన్న ఫోకస్ రీసెట్‌గా ఉపయోగించబడుతుంది.',
      tr: 'İnsanlar hızlı bir zihinsel değişim istediğinde bazen kısa bir odaklanma sıfırlaması olarak kullanılır.',
      pa: 'ਕਦੇ-ਕਦੇ ਇੱਕ ਸੰਖੇਪ ਫੋਕਸ ਰੀਸੈਟ ਵਜੋਂ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ ਜਦੋਂ ਲੋਕ ਇੱਕ ਤੇਜ਼ ਮਾਨਸਿਕ ਤਬਦੀਲੀ ਚਾਹੁੰਦੇ ਹਨ।',
      ta: 'மக்கள் விரைவான மன மாற்றத்தை விரும்பும்போது சில நேரங்களில் குறுகிய கவனம் மீட்டமைப்பாகப் பயன்படுத்தப்படுகிறது.',
      jv: 'Sok-sok digunakake minangka reset fokus cendhak nalika wong pengin owah-owahan mental sing cepet.',
      it: 'A volte usato come breve reset della messa a fuoco quando si desidera un rapido cambiamento mentale.',
      id: 'Terkadang digunakan sebagai reset fokus singkat ketika orang menginginkan perubahan mental yang cepat.'
    } 
  },
  { 
    key: 'violet', 
    label: { 
      ja: 'ヴァイオレット', en: 'Violet', 'zh-Hans': '紫噪音', es: 'Violeta', ko: '바이올レット', fr: 'Violet', de: 'Violett',
      hi: 'बैंगनी', bn: 'বেগুনী', pt: 'Violeta', ru: 'Фиолетовый', yue: '紫噪音', vi: 'Tím', mr: 'जांभळा', te: 'వైలెట్', tr: 'Mor', pa: 'ਬੈਂਗਣੀ', ta: 'ஊதா', jv: 'Ungu', it: 'Violetto', id: 'Violet'
    }, 
    short: { 
      ja: '高めの刺激で注意を向けやすいと感じる人がいますが、長時間は疲れやすいことがあります。', 
      en: 'Some listeners feel more alert with it, though long sessions can be fatiguing.',
      'zh-Hans': '高频率刺激让人更容易集中注意力，但长时间使用可能会疲劳。',
      es: 'Algunos oyentes se sienten más alerta, aunque sesiones largas pueden fatigar.',
      ko: '높은 자극으로 주의를 끌기 쉽지만, 장시간 사용 시 피로할 수 있습니다.',
      fr: 'Certaines personnes le trouvent stimulant, mais des sessions prolongées peuvent fatiguer.',
      de: 'Manche fühlen sich wacher, aber lange Sitzungen können ermüdend sein.',
      hi: 'कुछ सुनने वाले इससे अधिक सतर्क महसूस करते हैं, हालांकि लंबे सत्र थकाने वाले हो सकते हैं।',
      bn: 'कुछ শ্রোতা এটি দিয়ে আরও সতর্ক বোধ করেন, যদিও দীর্ঘ সেশন ক্লান্তিকর হতে পারে।',
      pt: 'Alguns ouvintes sentem-se mais alertas com ele, embora sessões longas possam ser cansativas.',
      ru: 'Некоторые слушатели чувствуют себя бодрее с ним, хотя длительные сеансы могут утомлять.',
      yue: '高頻率刺激令人更容易集中注意力，但長時間使用可能會疲勞。',
      vi: 'Một số người nghe cảm thấy tỉnh táo hơn với nó, mặc dù các phiên kéo dài có thể gây mệt mỏi.',
      mr: 'काही श्रोत्यांना यामुळे अधिक सतर्क वाटते, जरी दीर्घ सत्र थकवणारे असू शकतात.',
      te: 'కొంతమంది శ్రోతలు దీనితో మరింత అప్రమత్తంగా ఉన్నట్లు భావిస్తారు, అయితే సుదీర్ఘ సెషన్లు అలసటను కలిగిస్తాయి.',
      tr: 'Bazı dinleyiciler bununla daha uyanık hisseder, ancak uzun seanslar yorucu olabilir.',
      pa: 'ਕੁਝ ਸੁਣਨ ਵਾਲੇ ਇਸ ਨਾਲ ਵਧੇਰੇ ਸੁਚੇਤ ਮਹਿਸੂਸ ਕਰਦੇ ਹਨ, ਹਾਲਾਂਕਿ ਲੰਬੇ ਸੈਸ਼ਨ ਥਕਾਊ ਹੋ ਸਕਦੇ ਹਨ।',
      ta: 'சில கேட்பவர்கள் இதனுடன் அதிக விழிப்புடன் இருப்பதாக உணர்கிறார்கள், இருப்பினும் நீண்ட அமர்வுகள் சோர்வாக இருக்கலாம்.',
      jv: 'Sawetara wong ngrasa luwih waspada karo iki, sanajan sesi sing suwe bisa nggawe kesel.',
      it: 'Alcuni ascoltatori si sentono più vigili con esso, anche se sessioni lunghe possono essere affaticanti.',
      id: 'Beberapa pendengar merasa lebih waspada dengannya, meskipun sesi yang lama bisa melelahkan.'
    } 
  },
  {
    key: 'off',
    label: { 
      ja: 'オフ', en: 'Off', 'zh-Hans': '关闭', es: 'Apagado', hi: 'बंद', bn: 'বন্ধ', pt: 'Desligado', ru: 'Выкл', yue: '關閉', vi: 'Tắt', mr: 'बंद', te: 'ఆఫ్', tr: 'Kapalı', ko: '끔', pa: 'ਬੰਦ', ta: 'ஆஃப்', jv: 'Mati', it: 'Off', fr: 'Désactivé', de: 'Aus', id: 'Mati'
    },
    short: { 
      ja: 'ノイズを停止します。', en: 'Turn off noise.', 'zh-Hans': '关闭噪音。', es: 'Detener ruido.', hi: 'शोर बंद करें।', bn: 'শব্দ বন্ধ করুন।', pt: 'Desligar ruído.', ru: 'Выключить шум.', yue: '關閉噪音。', vi: 'Tắt tiếng ồn.', mr: 'आवाज बंद करा.', te: 'శబ్దాన్ని ఆపివేయండి.', tr: 'Gürültüyü kapat.', ko: '노이즈를 끕니다.', pa: 'ਸ਼ੋਰ ਬੰਦ ਕਰੋ।', ta: 'ஒலியை நிறுத்து.', jv: 'Patini swara.', it: 'Spegni il rumore.', fr: 'Arrêter le bruit.', de: 'Rauschen ausschalten.', id: 'Matikan suara.'
    }
  }
];

export const binauralBands: Array<{
  key: string;
  min: number;
  max: number;
  symbol: string;
  label: LocalizedText;
  reading: LocalizedText;
  effect: LocalizedText;
}> = [
  {
    key: 'delta',
    min: 0.5,
    max: 4,
    symbol: 'Δ',
    label: { 
      ja: 'デルタ', en: 'Delta', 'zh-Hans': '德尔塔', es: 'Delta', hi: 'डेल्टा', bn: 'ডেল্টা', pt: 'Delta', ru: 'Дельта', yue: '德爾塔', vi: 'Delta', mr: 'डेल्टा', te: 'డెల్టా', tr: 'Delta', ko: '델타', pa: 'ਡੈਲਟਾ', ta: 'டெல்டா', jv: 'Delta', it: 'Delta', fr: 'Delta', de: 'Delta', id: 'Delta'
    },
    reading: { ja: '0.5-4Hz', en: '0.5-4Hz' },
    effect: {
      ja: '深い休息モードに寄せたいときの目安です。夜の静かな時間に合わせやすい帯域です。',
      en: 'A common target when aiming for a deeper rest mood, especially in quiet night sessions.',
      'zh-Hans': '旨在进入深度休息模式时的参考，适合安静的夜晚使用。',
      es: 'Un objetivo común cuando se busca un estado de descanso profundo.',
      hi: 'गहरी विश्राम की स्थिति प्राप्त करने के लिए एक सामान्य लक्ष्य।',
      bn: 'গভীর বিশ্রামের মেজাজ অর্জনের লক্ষ্য থাকলে এটি একটি সাধারণ লক্ষ্য।',
      pt: 'Um alvo comum ao procurar um humor de descanso profundo.',
      ru: 'Обычная цель при стремлении к состоянию глубокого отдыха.',
      yue: '旨在進入深度休息模式時嘅參考，適合安靜嘅夜晚使用。',
      vi: 'Một mục tiêu phổ biến khi hướng tới tâm trạng nghỉ ngơi sâu hơn.',
      mr: 'खोल विश्रांतीच्या मनःस्थितीसाठी एक सामान्य लक्ष्य.',
      te: 'లోతైన విశ్రాంతి కోసం ఒక సాధారణ లక్ష్యం.',
      tr: 'Derin bir dinlenme modu hedeflendiğinde yaygın bir hedef.',
      ko: '깊은 휴식 모드를 목표로 할 때의 일반적인 타겟입니다.',
      pa: 'ਡੂੰਘੇ ਆਰਾਮ ਦੇ ਮੂਡ ਲਈ ਇੱਕ ਆਮ ਟੀਚਾ।',
      ta: 'ஆழ்ந்த ஓய்வு நிலையை நோக்கமாகக் கொள்ளும்போது ஒரு பொதுவான இலக்கு.',
      jv: 'Target umum nalika ngarahake swasana istirahat sing luwih jero.',
      it: 'Un obiettivo comune quando si punta a un umore di riposo profondo.',
      fr: 'Une cible courante pour viser un mode de repos profond.',
      de: 'Ein gemeinsames Ziel, wenn ein tieferer Ruhezustand angestrebt wird.',
      id: 'Target umum saat bertujuan untuk suasana istirahat yang lebih dalam.'
    }
  },
  {
    key: 'theta',
    min: 4,
    max: 8,
    symbol: 'θ',
    label: { 
      ja: 'シータ', en: 'Theta', 'zh-Hans': '西塔', es: 'Theta', hi: 'थीटा', bn: 'থিটা', pt: 'Theta', ru: 'Тета', yue: '西塔', vi: 'Theta', mr: 'थीटा', te: 'థీటా', tr: 'Teta', ko: '세타', pa: 'ਥੀਟਾ', ta: 'தீட்டா', jv: 'Theta', it: 'Theta', fr: 'Thêta', de: 'Theta', id: 'Theta'
    },
    reading: { ja: '4-8Hz', en: '4-8Hz' },
    effect: {
      ja: '落ち着きや内省の感覚と結びつけられることがあります。体感は人によって大きく変わります。',
      en: 'Sometimes linked to calm or inward attention, with large person-to-person variation.',
      'zh-Hans': '有时与平静或内省相关。感受因人而异。',
      es: 'A veces relacionado con la calma o la atención interior.',
      hi: 'कभी-कभी शांति या आंतरिक ध्यान से जुड़ा होता है।',
      bn: 'কখনও কখনও শান্ত বা অভ্যন্তরীণ মনোযোগের সাথে যুক্ত হয়।',
      pt: 'Às vezes ligado à calma ou atenção interna.',
      ru: 'Иногда связывается со спокойствием или внутренним вниманием.',
      yue: '有時同平靜或內省相關。感受因人而異。',
      vi: 'Đôi khi liên quan đến sự bình tĩnh hoặc sự chú ý hướng nội.',
      mr: 'कधीकधी शांतता किंवा आंतरिक लक्ष्याशी जोडलेले असते.',
      te: 'కొన్నిసార్లు ప్రశాంతత లేదా అంతర్గత శ్రద్ధతో ముడిపడి ఉంటుంది.',
      tr: 'Bazen sakinlik veya içsel dikkatle bağlantılıdır.',
      ko: '평온함이나 내면의 집중력과 연결되기도 합니다.',
      pa: 'ਕਦੇ-ਕਦੇ ਸ਼ਾਂਤੀ ਜਾਂ ਅੰਦਰੂਨੀ ਧਿਆਨ ਨਾਲ ਜੁੜਿਆ ਹੁੰਦਾ ਹੈ।',
      ta: 'சில நேரங்களில் அமைதி அல்லது உள்நோக்கிய கவனத்துடன் இணைக்கப்படுகிறது.',
      jv: 'Sok-sok digandhengake karo katentreman utawa perhatian batin.',
      it: 'A volte legato alla calma o all\'attenzione interiore.',
      fr: 'Parfois lié au calme ou à l\'attention intérieure.',
      de: 'Wird manchmal mit Ruhe oder innerer Aufmerksamkeit in Verbindung gebracht.',
      id: 'Terkadang dikaitkan dengan ketenangan atau perhatian batin.'
    }
  },
  {
    key: 'alpha',
    min: 8,
    max: 13,
    symbol: 'α',
    label: { 
      ja: 'アルファ', en: 'Alpha', 'zh-Hans': '阿尔法', es: 'Alpha', hi: 'अल्फा', bn: 'আলফা', pt: 'Alpha', ru: 'Альфа', yue: '阿爾法', vi: 'Alpha', mr: 'अल्फा', te: 'ఆల్ఫా', tr: 'Alfa', ko: '알파', pa: 'ਅਲਫਾ', ta: 'ஆல்பா', jv: 'Alpha', it: 'Alpha', fr: 'Alpha', de: 'Alpha', id: 'Alpha'
    },
    reading: { ja: '8-13Hz', en: '8-13Hz' },
    effect: {
      ja: 'リラックスしつつ作業したいときに選ばれやすい、バランス型の帯域です。',
      en: 'A balanced range often chosen for relaxed but awake sessions.',
      'zh-Hans': '想要边放松边工作时容易选择的平衡波段。',
      es: 'Un rango equilibrado para sesiones de relajación activa.',
      hi: 'आरामदायक लेकिन जागृत सत्रों के लिए चुना गया एक संतुलित रेंज।',
      bn: 'বিশ্রাম কিন্তু জাগ্রত সেশনের জন্য প্রায়ই বেছে নেওয়া একটি সুষম পরিসর।',
      pt: 'Uma faixa equilibrada frequentemente escolhida para sessões relaxadas, mas acordadas.',
      ru: 'Сбалансированный диапазон, часто выбираемый для расслабленного бодрствования.',
      yue: '想要邊放鬆邊工作時容易選擇嘅平衡波段。',
      vi: 'Một phạm vi cân bằng thường được chọn cho các phiên thư giãn nhưng vẫn tỉnh táo.',
      mr: 'एक संतुलित श्रेणी जी बऱ्याचदा विश्रांतीसाठी पण जागृत असताना निवडली जाते.',
      te: 'విశ్రాంతిగా ఉన్నప్పటికీ మెలకువగా ఉండే సెషన్ల కోసం ఎంచుకునే సమతుల్య శ్రేణి.',
      tr: 'Rahat ama uyanık seanslar için genellikle seçilen dengeli bir aralık.',
      ko: '휴식을 취하면서 작업하고 싶을 때 선택하기 좋은 밸런스형 대역입니다.',
      pa: 'ਆਰਾਮਦਾਇਕ ਪਰ ਜਾਗਦੇ סੈਸ਼ਨਾਂ ਲਈ ਅਕਸਰ ਚੁਣੀ ਜਾਣ ਵਾਲੀ ਇੱਕ ਸੰਤੁਲਿਤ ਰੇਂਜ।',
      ta: 'ஓய்வாகவும் விழிப்புடனும் இருக்கும் அமர்வுகளுக்கு பெரும்பாலும் தேர்ந்தெடுக்கப்படும் ஒரு சீரான வரம்பு.',
      jv: 'Range sing seimbang asring dipilih kanggo sesi santai nanging tetep tangi.',
      it: 'Una gamma equilibrata spesso scelta per sessioni rilassate ma sveglie.',
      fr: 'Une gamme équilibrée souvent choisie pour des sessions de relaxation active.',
      de: 'Ein ausgewogener Bereich, der oft für entspanntes Wachsein gewählt wird.',
      id: 'Rentang seimbang yang sering dipilih untuk sesi santai namun tetap terjaga.'
    }
  },
  {
    key: 'beta',
    min: 13,
    max: 30,
    symbol: 'β',
    label: { 
      ja: 'ベータ', en: 'Beta', 'zh-Hans': '贝塔', es: 'Beta', hi: 'बीटा', bn: 'বিটা', pt: 'Beta', ru: 'Бета', yue: '貝塔', vi: 'Beta', mr: 'बीटा', te: 'బీటా', tr: 'Beta', ko: '베타', pa: 'ਬੀਟਾ', ta: 'பீட்டா', jv: 'Beta', it: 'Beta', fr: 'Bêta', de: 'Beta', id: 'Beta'
    },
    reading: { ja: '13-30Hz', en: '13-30Hz' },
    effect: {
      ja: '注意や課題集中に関連づけられる帯域です。人によっては刺激が強すぎる場合があります。',
      en: 'Often associated with attention and task focus, though it may feel overstimulating.',
      'zh-Hans': '与注意力和任务集中相关的波段。对某些人来说可能过于刺激。',
      es: 'Relacionado con la atención y el enfoque en tareas.',
      hi: 'अक्सर ध्यान और कार्य फोकस से जुड़ा होता है।',
      bn: 'প্রায়শই মনোযোগ এবং কাজের ফোকাসের সাথে যুক্ত।',
      pt: 'Frequentemente associado à atenção e foco em tarefas.',
      ru: 'Часто ассоциируется с вниманием и сосредоточенностью.',
      yue: '同注意力同任務集中相關嘅波段。對某些人嚟講可能太過刺激。',
      vi: 'Thường liên quan đến sự chú ý và tập trung vào nhiệm vụ.',
      mr: 'बऱ्याचदा लक्ष आणि कार्यावर लक्ष केंद्रित करण्याशी संबंधित असते.',
      te: 'తరచుగా శ్రద్ధ మరియు పనిపై దృష్టి పెట్టడంతో ముడిపడి ఉంటుంది.',
      tr: 'Genellikle dikkat ve görev odağı ile ilişkilendirilir.',
      ko: '주의력 및 과제 집중과 관련이 있는 대역입니다. 자극이 강할 수 있습니다.',
      pa: 'ਅਕਸਰ ਧਿਆਨ ਅਤੇ ਕੰਮ ਦੇ ਫੋਕਸ ਨਾਲ ਜੁੜਿਆ ਹੁੰਦਾ ਹੈ।',
      ta: 'கவனம் மற்றும் பணி சார்ந்த ஒருமுகப்படுத்தலுடன் பெரும்பாலும் தொடர்புடையது.',
      jv: 'Asring digandhengake karo perhatian lan fokus tugas.',
      it: 'Spesso associato all\'attenzione e alla concentrazione sul compito.',
      fr: 'Souvent associé à l\'attention et à la concentration sur une tâche.',
      de: 'Wird oft mit Aufmerksamkeit und Aufgabenfokus in Verbindung gebracht.',
      id: 'Sering dikaitkan dengan perhatian dan fokus tugas.'
    }
  },
  {
    key: 'gamma',
    min: 30,
    max: 40,
    symbol: 'γ',
    label: { 
      ja: 'ガンマ', en: 'Gamma', 'zh-Hans': '伽马', es: 'Gamma', hi: 'गामा', bn: 'গামা', pt: 'Gamma', ru: 'Гамма', yue: '伽馬', vi: 'Gamma', mr: 'गामा', te: 'గామా', tr: 'Gama', ko: '감마', pa: 'ਗਾਮਾ', ta: 'காமா', jv: 'Gamma', it: 'Gamma', fr: 'Gamma', de: 'Gamma', id: 'Gamma'
    },
    reading: { ja: '30-40Hz', en: '30-40Hz' },
    effect: {
      ja: '切り替えや短時間の高集中に向けた高めの帯域です。刺激が強く感じる場合があります。',
      en: 'A higher band often used for short, high-focus pushes; it can feel intense.',
      'zh-Hans': '用于转换心情或短时间高度集中的较高波段。可能感觉强度很大。',
      es: 'Una banda superior para periodos cortos de alta concentración.',
      hi: 'लघु, उच्च-फोकस के लिए उपयोग किया जाने वाला एक उच्च बैंड।',
      bn: 'সংক্ষিপ্ত, উচ্চ-ফোকাস সময়ের জন্য ব্যবহৃত একটি উচ্চ ব্যান্ড।',
      pt: 'Uma faixa mais alta frequentemente usada para picos curtos de alto foco.',
      ru: 'Более высокий диапазон для кратковременной высокой концентрации.',
      yue: '用喺轉換心情或短時間高度集中嘅較高波段。可能感覺強度好大。',
      vi: 'Một dải cao hơn thường được sử dụng cho các lần tập trung cao độ trong thời gian ngắn.',
      mr: 'लहान, उच्च-फोकस असलेल्या कालावधीसाठी वापरला जाणारा उच्च बँड.',
      te: 'చిన్న, అధిక-ఫోకస్ కోసం ఉపయోగించే అధిక బ్యాండ్.',
      tr: 'Kısa, yüksek odaklı çabalar için kullanılan daha yüksek bir bant.',
      ko: '전환이나 단시간 고집중을 위한 높은 대역입니다. 강하게 느껴질 수 있습니다.',
      pa: 'ਛੋਟੇ, ਉੱਚ-ਫੋਕਸ ਲਈ ਵਰਤੀ ਜਾਣ ਵਾਲੀ ਇੱਕ ਉੱਚ ਬੈਂਡ।',
      ta: 'குறுகிய, அதிக செறிவு நிலைகளுக்காகப் பயன்படுத்தப்படும் ஒரு உயர் பேண்ட்.',
      jv: 'Band sing luwih dhuwur asring digunakake kanggo fokus dhuwur im wektu cendhak.',
      it: 'Una banda superiore spesso utilizzata per brevi spinte ad alta concentrazione.',
      fr: 'Une gamme plus élevée utilisée pour de courtes périodes de haute concentration.',
      de: 'Ein höherer Bereich für kurze Phasen hoher Konzentration.',
      id: 'Pita yang lebih tinggi sering digunakan untuk dorongan fokus tinggi yang singkat.'
    }
  }
];

export const presets: Preset[] = [
  {
    key: 'focus',
    label: { 
      ja: '1. 深い集中 (Focus)', en: '1. Deep Focus', 'zh-Hans': '1. 深度集中', es: '1. Enfoque profundo', hi: '1. गहरी एकाग्रता', bn: '1. গভীর একাগ্রতা', pt: '1. Foco profundo', ru: '1. Глубокая концентрация', yue: '1. 深度集中', vi: '1. Tập trung sâu', mr: '1. खोल एकाग्रता', te: '1. లోతైన ఏకాగ్రత', tr: '1. Derin Odak', ko: '1. 깊은 집중', pa: '1. ਡੂੰਘੀ ਇਕਾਗਰਤਾ', ta: '1. ஆழ்ந்த செறிவு', jv: '1. Fokus Jero', it: '1. Concentrazione profonda', fr: '1. Concentration profonde', de: '1. Tiefer Fokus', id: '1. Fokus Mendalam'
    },
    description: { 
      ja: 'プログラミングや執筆など、雑念を消して没入したい時に。', 
      en: 'For coding or writing.',
      'zh-Hans': '适用于编程或写作等需要排除杂念、全身心投入的场合。',
      es: 'Para programar o escribir.',
      hi: 'कोडिंग या लेखन के लिए।',
      bn: 'কোডিং বা লেখার জন্য।',
      pt: 'Para programação ou escrita.',
      ru: 'Для программирования или письма.',
      yue: '適用於編程或寫作等需要排除雜念、全身心投入嘅場合。',
      vi: 'Để lập trình hoặc viết lách.',
      mr: 'कोडिंग किंवा लेखनासाठी.',
      te: 'కోడింగ్ లేదా రాయడం కోసం.',
      tr: 'Kodlama veya yazma için.',
      ko: '프로그래밍이나 집필 등 잡념을 없애고 몰입하고 싶을 때.',
      pa: 'ਕੋਡਿੰਗ ਜਾਂ ਲਿਖਣ ਲਈ।',
      ta: 'குறியீட்டு முறை அல்லது எழுதுவதற்கு.',
      jv: 'Kanggo coding utawa nulis.',
      it: 'Per programmare o scrivere.',
      fr: 'Pour coder ou écrire.',
      de: 'Zum Programmieren oder Schreiben.',
      id: 'Untuk coding atau menulis.'
    },
    noiseType: 'brown',
    beatBand: 'beta',
    baseFrequency: 440
  },
  {
    key: 'creative',
    label: { 
      ja: '2. 創造的思考 (Creative)', en: '2. Creative Flow', 'zh-Hans': '2. 创造性思维', es: '2. Flujo creativo', hi: '2. रचनात्मक प्रवाह', bn: '2. সৃজনশীল प्रवाह', pt: '2. Fluxo criativo', ru: '2. Творческий поток', yue: '2. 創造性思維', vi: '2. Dòng chảy sáng tạo', mr: '2. सर्जनशील प्रवाह', te: '2. సృజనాత్మక ప్రవాహం', tr: '2. Yaratıcı Akış', ko: '2. 창의적 사고', pa: '2. ਰਚਨਾਤਮਕ ਪ੍ਰਵਾਹ', ta: '2. படைப்பு ఓட்டம்', jv: '2. Aliran Kreatif', it: '2. Flusso creativo', fr: '2. Flux créatif', de: '2. Kreativer Fluss', id: '2. Aliran Kreatif'
    },
    description: { 
      ja: '企画、設計、読書など、リラックスしつつ意識を広げたい時に。', 
      en: 'For planning or reading.',
      'zh-Hans': '适用于策划、设计、阅读等需要放松同时扩展思路的场合。',
      es: 'Para planificar o leer.',
      hi: 'योजना बनाने या पढ़ने के लिए।',
      bn: 'পরিকল্পনা বা পড়ার জন্য।',
      pt: 'Para planejamento ou leitura.',
      ru: 'Для планирования или чтения.',
      yue: '適用於策劃、設計、閱讀等需要放鬆同時擴展思路嘅場合。',
      vi: 'Để lập kế hoạch hoặc đọc sách.',
      mr: 'नियोजन किंवा वाचनासाठी.',
      te: 'ప్రణాళిక లేదా పఠనం కోసం.',
      tr: 'Planlama veya okuma için.',
      ko: '기획, 설계, 독서 등 휴식을 취하면서 의식을 넓히고 싶을 때.',
      pa: 'ਯੋਜਨਾ ਬਣਾਉਣ ਜਾਂ ਪੜ੍ਹਨ ਲਈ।',
      ta: 'திட்டமிடல் அல்லது வாசிப்பிற்கு.',
      jv: 'Kanggo ngrancang utawa maca.',
      it: 'Per pianificare o leggere.',
      fr: 'Pour planifier ou lire.',
      de: 'Zum Planen oder Lesen.',
      id: 'Untuk merencanakan atau membaca.'
    },
    noiseType: 'pink',
    beatBand: 'alpha',
    baseFrequency: 528
  },
  {
    key: 'study',
    label: { 
      ja: '3. 短期集中 (Study)', en: '3. Quick Study', 'zh-Hans': '3. 短期集中', es: '3. Estudio rápido', hi: '3. त्वरित अध्ययन', bn: '3. দ্রুত অধ্যয়ন', pt: '3. Estudo rápido', ru: '3. Быстрая учеба', yue: '3. 短期集中', vi: '3. Học nhanh', mr: '3. जलद अभ्यास', te: '3. త్వరిత అధ్యయనం', tr: '3. Hızlı Çalışma', ko: '3. 단기 집중', pa: '3. ਤੁਰੰਤ ਅਧਿਐਨ', ta: '3. விரைவான படிப்பு', jv: '3. Sinau Cepet', it: '3. Studio rapido', fr: '3. Étude rapide', de: '3. Schnelles Lernen', id: '3. Belajar Cepat'
    },
    description: { 
      ja: '試験前の詰め込みなど、短時間で情報を処理したい時に。', 
      en: 'For pre-exam pushes.',
      'zh-Hans': '适用于考前突击等需要在短时间内处理大量信息的场合。',
      es: 'Para repasos antes de un examen.',
      hi: 'परीक्षा से पहले की तैयारी के लिए।',
      bn: 'পরীক্ষার আগের প্রস্তుতির জন্য।',
      pt: 'Para estudos intensos pré-exame.',
      ru: 'Для подготовки перед экзаменом.',
      yue: '適用於考前突擊等需要喺短時間內處理大量資訊嘅場合。',
      vi: 'Cho giai đoạn ôn thi.',
      mr: 'परीक्षेपूर्वीच्या अभ्यासासाठी.',
      te: 'పరీక్షకు ముందు ప్రిపరేషన్ కోసం.',
      tr: 'Sınav öncesi çalışmalar için.',
      ko: '시험 전 벼락치기 등 단시간에 정보를 처리하고 싶을 때.',
      pa: 'ਪ੍ਰੀਖਿਆ ਤੋਂ ਪਹਿਲਾਂ ਦੀ ਤਿਆਰੀ ਲਈ।',
      ta: 'தேர்வு நேரப் படிப்பிற்கு.',
      jv: 'Kanggo sinau sadurunge ujian.',
      it: 'Per ripassi pre-esame.',
      fr: 'Pour les révisions intensives.',
      de: 'Für das Lernen vor Prüfungen.',
      id: 'Untuk persiapan ujian.'
    },
    noiseType: 'white',
    beatBand: 'gamma',
    baseFrequency: 741
  },
  {
    key: 'meditation',
    label: { 
      ja: '4. 瞑想・休息 (Meditate)', en: '4. Meditation', 'zh-Hans': '4. 冥想与休息', es: '4. Meditación', hi: '4. ध्यान', bn: '4. ধ্যান', pt: '4. Meditação', ru: '4. Медитация', yue: '4. 冥想同休息', vi: '4. Thiền định', mr: '4. ध्यान', te: '4. ధ్యానం', tr: '4. Meditasyon', ko: '4. 명상 및 휴식', pa: '4. ਧਿਆਨ', ta: '4. தியானம்', jv: '4. Meditasi', it: '4. Meditazione', fr: '4. Méditation', de: '4. Meditation', id: '4. Meditasi'
    },
    description: { 
      ja: '休憩時間や、心を落ち着かせたい時に。', 
      en: 'To calm the mind. Noise off.',
      'zh-Hans': '适用于休息时间或想要静下心来时。噪音已关闭。',
      es: 'Para calmar la mente. Ruido apagado.',
      hi: 'मन को शांत करने के लिए। शोर बंद।',
      bn: 'মন শান্ত করার জন্য। শব্দ বন্ধ।',
      pt: 'Para acalmar a mente. Ruído desligado.',
      ru: 'Чтобы успокоить разум. Шум выкл.',
      yue: '適用於休息時間或想要靜下心嚟時。噪音已關閉。',
      vi: 'Để làm dịu tâm trí. Tắt tiếng ồn.',
      mr: 'मन शांत करण्यासाठी. आवाज बंद.',
      te: 'మనస్సును ప్రశాంతంగా ఉంచుకోవడానికి. శబ్దం ఆఫ్.',
      tr: 'Zihni sakinleştirmek için. Gürültü kapalı.',
      ko: '휴식 시간이나 마음을 진정시키고 싶을 때. 노이즈 꺼짐.',
      pa: 'ਮਨ ਨੂੰ ਸ਼ਾਂਤ ਕਰਨ ਲਈ। ਸ਼ੋਰ ਬੰਦ।',
      ta: 'மனதை அமைதிப்படுத்த. ஒலி ஆஃப்.',
      jv: 'Kanggo nenangke pikiran. Swara mati.',
      it: 'Per calmare la mente. Rumore off.',
      fr: 'Pour calmer l\'esprit. Bruit désactivé.',
      de: 'Um den Geist zu beruhigen. Rauschen aus.',
      id: 'Untuk menenangkan pikiran. Suara mati.'
    },
    noiseType: 'off',
    beatBand: 'theta',
    baseFrequency: 396
  },
  {
    key: 'sleep',
    label: { 
      ja: '5. 入眠 (Sleep)', en: '5. Deep Sleep', 'zh-Hans': '5. 入睡', es: '5. Sueño profundo', hi: '5. गहरी नींद', bn: '5. গভীর ঘুম', pt: '5. Sono profundo', ru: '5. Глубокий сон', yue: '5. 入睡', vi: '5. Ngủ sâu', mr: '5. खोल झोप', te: '5. గాఢ నిద్ర', tr: '5. Derin Uyku', ko: '5. 수면', pa: '5. ਡੂੰਘੀ ਨੀਂਦ', ta: '5. ஆழ்ந்த உறக்கம்', jv: '5. Turu Jero', it: '5. Sonno profondo', fr: '5. Sommeil profond', de: '5. Tiefer Schlaf', id: '5. Tidur Nyenyak'
    },
    description: { 
      ja: '寝付きが悪い時や、眠りが浅い時に。', 
      en: 'For restless nights.',
      'zh-Hans': '适用于入睡困难或睡眠较浅时。',
      es: 'Para noches de insomnio.',
      hi: 'बेचैन रातों के लिए।',
      bn: 'অশান্ত রাতের জন্য।',
      pt: 'Para noites inquietas.',
      ru: 'Для беспокойных ночей.',
      yue: '適用於入睡困難或睡眠較淺時。',
      vi: 'Cho những đêm trằn trọc.',
      mr: 'स्वस्थ झोप लागत नसेल तर.',
      te: 'నిద్రలేని రాత్రుల కోసం.',
      tr: 'Huzursuz geceler için.',
      ko: '잠이 잘 오지 않거나 깊게 잠들지 못할 때.',
      pa: 'ਬੇਚੈਨ ਰਾਤਾਂ ਲਈ।',
      ta: 'தூக்கமில்லாத இரவுகளுக்கு.',
      jv: 'Kanggo wengi sing ora bisa turu.',
      it: 'Per notti agitate.',
      fr: 'Pour les nuits agitées.',
      de: 'Für unruhige Nächte.',
      id: 'Untuk malam yang gelisah.'
    },
    noiseType: 'brown',
    beatBand: 'delta',
    baseFrequency: 174
  }
];

export const evidenceCards: EvidenceCard[] = [
  { 
    key: 'noise-colors', 
    title: { 
      ja: 'ノイズ色の違い', en: 'Differences between noise colors', 'zh-Hans': '噪音颜色的区别', es: 'Diferencias entre colores de ruido', hi: 'शोर के रंगों के बीच अंतर', bn: 'শব্দের রঙের মধ্যে পার্থক্য', pt: 'Diferenças entre cores de ruído', ru: 'Различия между цветами шума', yue: '噪音顏色嘅區別', vi: 'Sự khác biệt giữa các màu tiếng ồn', mr: 'आवाजाच्या रंगांमधील फरक', te: 'శబ్దం రంగుల మధ్య తేడాలు', tr: 'Gürültü renkleri arasındaki farklar', ko: '노이즈 색상의 차이', pa: 'ਸ਼ੋਰ ਦੇ ਰੰਗਾਂ ਵਿੱਚ ਅੰਤਰ', ta: 'ஒலி நிறங்களுக்கு இடையிலான வேறுபாடுகள்', jv: 'Bedane warna swara', it: 'Differenze tra i colori del rumore', fr: 'Différences entre les couleurs de bruit', de: 'Unterschiede zwischen Rauschfarben', id: 'Perbedaan antara warna kebisingan'
    }, 
    summary: { 
      ja: '白・ピンク・ブラウン・ブルー・ヴァイオレットは、周波数ごとの強さが違う音です。', 
      en: 'White, pink, brown, blue, and violet noise differ by frequency weighting.',
      'zh-Hans': '白、粉、褐、蓝、紫噪音的区别在于不同频率的强度权重。',
      es: 'El ruido blanco, rosa, marrón, azul и violeta se diferencian por el peso de la frecuencia.',
      hi: 'सफेद, गुलाबी, भूरा, नीला और बैंगनी शोर आवृत्ति भार के आधार पर भिन्न होते हैं।',
      bn: 'সাদা, গোলাপী, বাদামী, নীল এবং বেগুনী শব্দ ফ্রিকোয়েন্সি ওয়েটিং দ্বারা পৃথক হয়।',
      pt: 'Os ruídos branco, rosa, castanho, azul e violeta diferem pela ponderação de frequência.',
      ru: 'Белый, розовый, коричневый, голубой и фиолетовый шум различаются по частотному весу.',
      yue: '白、粉、褐、藍、紫噪音嘅區別在於唔同頻率嘅強度權重。',
      vi: 'Tiếng ồn trắng, hồng, nâu, xanh dương và tím khác nhau về trọng số tần số.',
      mr: 'पांढरा, गुलाबी, तपकिरी, निळा आणि जांभळा आवाज फ्रिक्वेन्सी वेटिंगनुसार बदलतो.',
      te: 'తెలుపు, గులాబీ, గోధుమ, నీలం మరియు వైలెట్ శబ్దాలు ఫ్రీక్వెンసీ వెయిటింగ్ ద్వారా మారుతాయి.',
      tr: 'Beyaz, pembe, kahverengi, mavi ve mor gürültü frekans ağırlığına göre farklılık gösterir.',
      ko: '화이트, 핑크, 브라운, 블루, 바이올렛 노이즈는 주파수별 강도가 다릅니다.',
      pa: 'ਚਿੱਟਾ, ਗੁਲਾਬੀ, ਭੂਰਾ, ਨੀਲਾ ਅਤੇ ਬੈਂਗਣੀ ਸ਼ੋਰ ਫ੍ਰੀਕੁਐਂਸੀ ਵੇਟਿੰਗ ਦੁਆরা ਵੱਖਰੇ ਹੁੰਦੇ ਹਨ।',
      ta: 'வெள்ளை, இளஞ்சிவப்பு, பழுப்பு, நீலம் மற்றும் ஊதா ஒலிகள் அதிர்வெண் எடையால் வேறுபடுகின்றன.',
      jv: 'Swara putih, abang enom, coklat, biru, lan ungu beda-beda miturut bobot frekuensi.',
      it: 'Il rumore bianco, rosa, marrone, blu e violetto differiscono per la ponderazione della frequenza.',
      fr: 'Les bruits blanc, rose, brun, bleu et violet diffèrent par leur pondération fréquentielle.',
      de: 'Weißes, rosa, braunes, blaues und violettes Rauschen unterscheiden sich durch die Frequenzgewichtung.',
      id: 'Kebisingan putih, merah muda, cokelat, biru, dan ungu berbeda dalam pembobotan frekuensi.'
    }, 
    strength: 'Strong', 
    caveat: { 
      ja: '個人差があります。', en: 'User experience varies a lot.', 'zh-Hans': '存在个人差异。', es: 'Varía según la persona.', hi: 'व्यक्तिगत भिन्नता हो सकती है।', bn: 'ব্যক্তিগত পার্থক্য হতে পারে।', pt: 'Varia entre as pessoas.', ru: 'Есть индивидуальные различия.', yue: '存在個人差異。', vi: 'Có sự khác biệt cá nhân.', mr: 'वैयक्तिक भिन्नता असू शकते.', te: 'వ్యక్తిగత వ్యత్యాసాలు ఉండవచ్చు.', tr: 'Kişisel farklılıklar vardır.', ko: '개인차가 있습니다.', pa: 'ਵਿਅਕਤੀਗਤ ਅੰਤਰ ਹੋ ਸਕਦੇ ਹਨ।', ta: 'தனிப்பட்ட வேறுபாடுகள் உள்ளன.', jv: 'Ana bedane saben wong.', it: 'Varia da persona a persona.', fr: 'Varie selon les individus.', de: 'Individuelle Unterschiede möglich.', id: 'Ada perbedaan individu.'
    }, 
    links: [{ label: 'Pink noise review', url: 'https://pubmed.ncbi.nlm.nih.gov/34964434/' }] 
  },
  { 
    key: 'binaural-beats', 
    title: { 
      ja: 'ビートについて', en: 'About Beats', 'zh-Hans': '关于节拍', es: 'Sobre los pulsos', hi: 'बीट्स के बारे में', bn: 'বিটস সম্পর্কে', pt: 'Sobre as batidas', ru: 'О ритмах', yue: '關於節拍', vi: 'Về nhịp', mr: 'बीट्सबद्दल', te: 'బీట్స్ గురించి', tr: 'Vuruşlar Hakkında', ko: '비트에 대하여', pa: 'ਬੀਟਸ ਬਾਰੇ', ta: 'பீட்ஸ் பற்றி', jv: 'Babagan Ketukan', it: 'Sui battiti', fr: 'À propos des battements', de: 'Über Beats', id: 'Tentang Ketukan'
    }, 
    summary: { 
      ja: '左右の耳に少し違う周波数を出して、差分のうなりを知覚させます。', 
      en: 'Two nearby tones are sent separately to each ear so the listener perceives a beat.',
      'zh-Hans': '向左右耳发送频率略有不同的声音，使大脑感知到差值产生的节拍。',
      es: 'Se envían dos tonos cercanos por separado a cada oído para percibir un pulso.',
      hi: 'दो आस-पास के स्वर प्रत्येक कान में अलग-अलग भेजे जाते हैं ताकि सुनने वाला एक बीट महसूस करे।',
      bn: 'দুটি কাছাকাছি সুর প্রতিটি কানে আলাদাভাবে পাঠানো হয় যাতে শ্রোতা একটি বিট অনুভব করেন।',
      pt: 'Dois tons próximos são enviados separadamente para cada ouvido para que o ouvinte perceba uma batida.',
      ru: 'Два близких тона подаются отдельно в каждое ухо, чтобы слушатель воспринимал ритм.',
      yue: '向左右耳發送頻率略有唔同嘅聲音，使大腦感知到差值產生嘅節拍。',
      vi: 'Hai âm sắc gần nhau được gửi riêng biệt đến mỗi tai để người nghe cảm nhận được một nhịp.',
      mr: 'दोन जवळचे टोन प्रत्येक कानात स्वतंत्रपणे पाठवले जातात जेणेकरून श्रोत्याला बीट जाणवेल.',
      te: 'రెండు సమీప టోన్లు ప్రతి చెవికి విడివిడిగా పంపబడతాయి, తద్వారా వినేవారు బీట్‌ను గ్రహిస్తారు.',
      tr: 'Dinleyicinin bir vuruş algılaması için iki yakın ton her kulağa ayrı ayrı gönderilir.',
      ko: '양쪽 귀에 조금씩 다른 주파수를 보내 그 차이만큼의 울림을 지각하게 합니다.',
      pa: 'ਦੋ ਨੇੜਲੇ ਟੋਨ ਹਰੇਕ ਕੰਨ ਵਿੱਚ ਵੱਖਰੇ ਤੌਰ \'ਤੇ ਭੇਜੇ ਜਾਂਦੇ ਹਨ ਤਾਂ ਜੋ ਸੁਣਨ ਵਾਲਾ ਇੱਕ ਬੀਟ ਮਹਿਸੂਸ ਕਰੇ।',
      ta: 'இரண்டு அருகிலுள்ள ஒலிகள் ஒவ்வொரு காதுக்கும் தனித்தனியாக அனுப்பப்படுகின்றன, இதனால் கேட்பவர் ஒரு பீட்டை உணர்கிறார்.',
      jv: 'Rong nada sing cedhak dikirim kanthi kapisah menyang saben kuping supaya pamiyarsa ngrasakake ketukan.',
      it: 'Due toni vicini vengono inviati separatamente a ciascun orecchio in modo che l\'ascoltatore percepisca un battito.',
      fr: 'Deux sons proches sont envoyés séparément à chaque oreille pour percevoir un battement.',
      de: 'Zwei nahe beieinander liegende Töne werden separat an jedes Ohr gesendet, sodass ein Beat wahrgenommen wird.',
      id: 'Dua nada yang berdekatan dikirim secara terpisah ke setiap telinga sehingga pendengar merasakan ketukan.'
    }, 
    strength: 'Mixed', 
    caveat: { 
      ja: '医療的な効果を断定しません。', en: 'No medical claims are made.', 'zh-Hans': '不作医疗效果断言。', es: 'No se hacen afirmaciones médicas.', hi: 'कोई चिकित्सा दावा नहीं किया गया है।', bn: 'কোন চিকিৎসা দাবি করা হয় না।', pt: 'Nenhuma alegação médica é feita.', ru: 'Медицинские утверждения не делаются.', yue: '唔作醫療效果斷言。', vi: 'Không có tuyên bố y tế nào được đưa ra.', mr: 'कोणताही वैद्यकीय दावा केला जात नाही.', te: 'వైద్యపరమైన క్లెయిమ్‌లు ఏవీ చేయబడలేదు.', tr: 'Tıbbi bir iddiada bulunulmamaktadır.', ko: '의료적인 효과를 단정하지 않습니다.', pa: 'ਕੋਈ ਡਾਕਟਰੀ ਦਾਅਵਾ ਨਹੀਂ ਕੀਤਾ ਗਿਆ ਹੈ।', ta: 'மருத்துவ ரீதியான உரிமைகோரல்கள் எதுவும் செய்யப்படவில்லை.', jv: 'Ora ana klaim medis.', it: 'Non si effettuano affermazioni mediche.', fr: 'Aucune réclamation médicale n\'est faite.', de: 'Keine medizinischen Ansprüche.', id: 'Tidak ada klaim medis.'
    }, 
    links: [{ label: 'Systematic review', url: 'https://pubmed.ncbi.nlm.nih.gov/37205669/' }] 
  }
];

const platformNotes: LocalizedList = {
  ja: ['iOS はブラウザの制限が強く、バックグラウンド再生は OS の状態に左右されます。', 'Android は PWA と Media Session が比較的素直に動きます。'],
  en: ['iOS has stricter browser limits.', 'Android usually handles PWA and Media Session well.'],
  'zh-Hans': ['iOS 浏览器限制较多，后台播放受系统状态影响。', 'Android 上的 PWA 和媒体会话支持较好。'],
  es: ['iOS tiene límites de navegador más estrictos.', 'Android suele manejar bien PWA y Media Session.'],
  hi: ['iOS में ब्राउज़र की सीमाएँ अधिक सख्त हैं।', 'Android आमतौर पर PWA और मीडिया सेशन को अच्छी तरह से संभालता है।'],
  bn: ['iOS-এ ব্রাউজারের সীমাবদ্ধতা বেশি।', 'Android সাধারণত PWA এবং মিডিয়া সেশন ভালভাবে পরিচালনা করে।'],
  pt: ['iOS tem limites de navegador mais rígidos.', 'O Android geralmente lida bem com PWA e Media Session.'],
  ru: ['У iOS более строгие ограничения браузера.', 'Android обычно хорошо справляется с PWA и Media Session.'],
  yue: ['iOS 瀏覽器限制較多，背景播放受系統狀態影響。', 'Android 上嘅 PWA 同媒體會話支援較好。'],
  vi: ['iOS có các giới hạn trình duyệt nghiêm ngặt hơn.', 'Android thường xử lý tốt PWA và Media Session.'],
  mr: ['iOS मध्ये ब्राउझरच्या मर्यादा अधिक कडक आहेत.', 'Android সহसा PWA आणि मीडिया सेशन चांगल्या प्रकारे हाताळते.'],
  te: ['iOS కఠినమైన బ్రౌజర్ పరిమితులను కలిగి ఉంది.', 'Android సాధారణంగా PWA మరియు మీడియా సెషన్‌ను బాగా నిర్వহিస్తుంది.'],
  tr: ['iOS daha katı tarayıcı sınırlarına sahiptir.', 'Android genellikle PWA ve Medya Oturumunu iyi yönetir.'],
  ko: ['iOS는 브라우저 제한이 강하며 백그라운드 재생은 OS 상태에 따라 다릅니다.', 'Android는 PWA와 미디어 세션이 비교적 원활하게 작동합니다.'],
  pa: ['iOS ਵਿੱਚ బ੍ਰਾਊਜ਼ਰ ਦੀਆਂ ਸੀਮਾਵਾਂ ਵਧੇਰੇ ਸਖ਼ਤ ਹਨ।', 'Android ਆਮ ਤੌਰ \'ਤੇ PWA ਅਤੇ ਮੀਡੀਆ ਸੈਸ਼ਨ ਨੂੰ ਚੰਗੀ ਤਰ੍ਹਾਂ ਸੰਭਾਲਦਾ ਹੈ।'],
  ta: ['iOS கடுமையான உலாவிக் கட்டுப்பாடுகளைக் கொண்டுள்ளது.', 'Android பொதுவாக PWA மற்றும் மீடியா செஷனைச் சிறப்பாகக் கையாளும்.'],
  jv: ['iOS duwe watesan browser sing luwih ketat.', 'Android biasane nangani PWA lan Media Session kanthi apik.'],
  it: ['iOS ha limiti del browser più severi.', 'Android di solito gestisce bene PWA e Media Session.'],
  fr: ['iOS a des limites de navigateur plus strictes.', 'Android gère généralement bien les PWA et les sessions multimédias.'],
  de: ['iOS hat strengere Browser-Limits.', 'Android kommt meist gut mit PWA und Media Session zurecht.'],
  id: ['iOS memiliki batasan browser yang lebih ketat.', 'Android biasanya menangani PWA dan Media Session baik.']
};

export function getPlatformNotes(locale: Locale): string[] {
  return resolveLocalizedList(platformNotes, locale);
}

export const timerOptions = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60] as const;

export function getNoiseLabel(locale: Locale, key: NoiseType): string {
  const item = noiseTypes.find((noiseType) => noiseType.key === key);
  return item ? resolveLocalizedText(item.label, locale) : key;
}